// packages/react-file-preview/src/renderers/Pdf/index.tsx
import { useState, useEffect, useRef, useCallback } from 'react';
import { Document, Page } from 'react-pdf';

// 导入 PDF.js 配置
import '../../utils/pdfConfig';

interface PdfRendererProps {
  url: string;
  zoom: number;
  currentPage: number;
  onPageChange: (page: number) => void;
  onTotalPagesChange: (total: number) => void;
  onPageWidthChange?: (width: number) => void;
}

export const PdfRenderer: React.FC<PdfRendererProps> = ({
  url,
  zoom,
  currentPage,
  onPageChange,
  onTotalPagesChange,
  onPageWidthChange,
}) => {
  const [numPages, setNumPages] = useState<number>(0);
  const [error, setError] = useState<string | null>(null);
  const containerRef = useRef<HTMLDivElement>(null);
  const pageRefs = useRef<Map<number, HTMLDivElement>>(new Map());

  useEffect(() => {
    setError(null);
  }, [url]);

  const onDocumentLoadSuccess = ({ numPages }: { numPages: number }) => {
    setNumPages(numPages);
    onTotalPagesChange(numPages);
    onPageChange(1);
  };

  const onDocumentLoadError = (error: Error) => {
    console.error('PDF 加载错误:', error);
    setError('PDF 文件加载失败');
  };

  // 滚动时更新当前页码
  const handleScroll = useCallback(() => {
    if (!containerRef.current) return;

    const container = containerRef.current;
    const scrollTop = container.scrollTop;
    const containerHeight = container.clientHeight;
    const scrollCenter = scrollTop + containerHeight / 2;

    // 找到当前可见的页面
    let currentVisiblePage = 1;
    let minDistance = Infinity;

    pageRefs.current.forEach((pageElement, pageNumber) => {
      const rect = pageElement.getBoundingClientRect();
      const containerRect = container.getBoundingClientRect();
      const pageCenter = rect.top - containerRect.top + rect.height / 2 + scrollTop;
      const distance = Math.abs(pageCenter - scrollCenter);

      if (distance < minDistance) {
        minDistance = distance;
        currentVisiblePage = pageNumber;
      }
    });

    if (currentVisiblePage !== currentPage) {
      onPageChange(currentVisiblePage);
    }
  }, [currentPage, onPageChange]);

  // 监听滚动事件
  useEffect(() => {
    const container = containerRef.current;
    if (!container) return;

    container.addEventListener('scroll', handleScroll);
    return () => container.removeEventListener('scroll', handleScroll);
  }, [handleScroll]);

  // 设置页面引用
  const setPageRef = useCallback((pageNumber: number, element: HTMLDivElement | null) => {
    if (element) {
      pageRefs.current.set(pageNumber, element);
    } else {
      pageRefs.current.delete(pageNumber);
    }
  }, []);

  return (
    <div
      ref={containerRef}
      className="rfp-flex rfp-flex-col rfp-items-center rfp-w-full rfp-h-full rfp-overflow-auto rfp-py-4 md:rfp-py-8 rfp-px-2 md:rfp-px-4"
    >
      {error && (
        <div className="rfp-text-white/70 rfp-text-center">
          <p className="rfp-text-lg">{error}</p>
        </div>
      )}

      {!error && (
        <Document
          file={url}
          onLoadSuccess={onDocumentLoadSuccess}
          onLoadError={onDocumentLoadError}
          loading={
            <div className="rfp-flex rfp-items-center rfp-justify-center rfp-min-h-screen">
              <div className="rfp-w-12 rfp-h-12 rfp-border-4 rfp-border-white/20 rfp-border-t-white rfp-rounded-full rfp-animate-spin" />
            </div>
          }
        >
          <div className="rfp-flex rfp-flex-col rfp-gap-4">
            {Array.from(new Array(numPages), (_, index) => {
              const pageNumber = index + 1;
              return (
                <div
                  key={`page_${pageNumber}`}
                  ref={(el) => setPageRef(pageNumber, el)}
                  className="rfp-relative"
                >
                  <Page
                    pageNumber={pageNumber}
                    scale={zoom}
                    loading={
                      <div className="rfp-flex rfp-items-center rfp-justify-center rfp-p-8 rfp-bg-white/5 rfp-rounded-lg rfp-min-h-[600px]">
                        <div className="rfp-w-8 rfp-h-8 rfp-border-4 rfp-border-white/20 rfp-border-t-white rfp-rounded-full rfp-animate-spin" />
                      </div>
                    }
                    renderTextLayer={false}
                    renderAnnotationLayer={false}
                    className="rfp-shadow-2xl"
                    onRenderSuccess={(page) => {
                      if (pageNumber === 1 && onPageWidthChange) {
                        // 上报 scale=1 时的原始页面宽度
                        onPageWidthChange(page.originalWidth || page.width / zoom);
                      }
                    }}
                  />
                  {/* 页码标签 */}
                  <div className="rfp-absolute rfp-top-2 rfp-right-2 rfp-bg-black/60 rfp-backdrop-blur-sm rfp-text-white rfp-text-xs rfp-px-3 rfp-py-1 rfp-rounded-full">
                    {pageNumber}
                  </div>
                </div>
              );
            })}
          </div>
        </Document>
      )}

      {/* 底部页码指示器 */}
      {numPages > 0 && (
        <div className="rfp-sticky rfp-bottom-2 md:rfp-bottom-4 rfp-mt-4 md:rfp-mt-8 rfp-bg-black/60 rfp-backdrop-blur-xl rfp-text-white rfp-px-4 rfp-py-2 md:rfp-px-6 md:rfp-py-3 rfp-rounded-full rfp-text-xs md:rfp-text-sm rfp-font-medium rfp-shadow-2xl rfp-border rfp-border-white/10">
          第 {currentPage} 页 / 共 {numPages} 页
        </div>
      )}
    </div>
  );
};

// packages/vue-file-preview/src/renderers/Pdf/index.vue
<script setup lang="ts">
import { ref, watch, onMounted, onBeforeUnmount, nextTick } from 'vue';
import { configurePdfWorker } from '@eternalheart/file-preview-core';
// @ts-ignore - pdfjs-dist 类型路径
import * as pdfjsLib from 'pdfjs-dist/build/pdf.mjs';
import { useTranslator } from '../../composables/useTranslator';

// 在模块加载时配置 PDF.js worker（默认走 CDN）
configurePdfWorker(pdfjsLib);

interface PdfPageProxy {
  getViewport(opts: { scale: number }): { width: number; height: number };
  render(opts: { canvasContext: CanvasRenderingContext2D; viewport: { width: number; height: number } }): {
    promise: Promise<void>;
  };
}

interface PdfDocumentProxy {
  numPages: number;
  getPage(pageNumber: number): Promise<PdfPageProxy>;
  destroy(): void;
}

const props = defineProps<{
  url: string;
  zoom: number;
  currentPage: number;
}>();

const emit = defineEmits<{
  (e: 'pageChange', page: number): void;
  (e: 'totalPagesChange', total: number): void;
  (e: 'pageWidthChange', width: number): void;
}>();

const { t } = useTranslator();

const numPages = ref(0);
const error = ref<string | null>(null);
const containerRef = ref<HTMLDivElement | null>(null);
let pdfDoc: PdfDocumentProxy | null = null;
const pageElements: HTMLDivElement[] = [];

const renderPage = async (pageNumber: number, scale: number, container: HTMLDivElement) => {
  if (!pdfDoc) return;
  const page = await pdfDoc.getPage(pageNumber);
  const viewport = page.getViewport({ scale });

  const canvas = document.createElement('canvas');
  canvas.width = viewport.width;
  canvas.height = viewport.height;
  canvas.style.maxWidth = '100%';
  canvas.style.height = 'auto';
  canvas.style.borderRadius = '0';
  canvas.style.display = 'block';
  canvas.style.boxShadow = '0 25px 50px -12px rgba(0,0,0,0.25)';
  canvas.style.filter = 'brightness(0.95) contrast(1.05)';

  const ctx = canvas.getContext('2d');
  if (!ctx) return;
  await page.render({ canvasContext: ctx, viewport }).promise;

  // 上报第一页原始宽度
  if (pageNumber === 1) {
    const baseViewport = page.getViewport({ scale: 1 });
    emit('pageWidthChange', baseViewport.width);
  }

  container.innerHTML = '';
  container.appendChild(canvas);

  // 页码标签
  const label = document.createElement('div');
  label.textContent = String(pageNumber);
  label.style.cssText =
    'position:absolute;top:8px;right:8px;background:rgba(0,0,0,0.6);backdrop-filter:blur(4px);color:white;font-size:12px;padding:4px 12px;border-radius:9999px;';
  container.appendChild(label);
};

const renderAll = async () => {
  if (!pdfDoc || !containerRef.value) return;
  const wrapper = containerRef.value.querySelector('.pdf-pages') as HTMLDivElement | null;
  if (!wrapper) return;
  wrapper.innerHTML = '';
  pageElements.length = 0;

  for (let i = 1; i <= numPages.value; i++) {
    const pageDiv = document.createElement('div');
    pageDiv.style.cssText = 'position:relative;display:flex;justify-content:center;';
    wrapper.appendChild(pageDiv);
    pageElements.push(pageDiv);
    // eslint-disable-next-line no-await-in-loop
    await renderPage(i, props.zoom, pageDiv);
  }
};

const loadPdf = async () => {
  error.value = null;
  numPages.value = 0;
  if (pdfDoc) {
    try {
      pdfDoc.destroy();
    } catch {
      // ignore
    }
    pdfDoc = null;
  }

  try {
    const loadingTask = pdfjsLib.getDocument({ url: props.url });
    pdfDoc = (await loadingTask.promise) as PdfDocumentProxy;
    numPages.value = pdfDoc.numPages;
    emit('totalPagesChange', pdfDoc.numPages);
    emit('pageChange', 1);
    await nextTick();
    await renderAll();
  } catch (err) {
    console.error('PDF 加载错误:', err);
    error.value = t.value('pdf.load_failed');
  }
};

const handleScroll = () => {
  if (!containerRef.value) return;

  const container = containerRef.value;
  const scrollTop = container.scrollTop;
  const containerHeight = container.clientHeight;
  const scrollCenter = scrollTop + containerHeight / 2;

  let currentVisiblePage = 1;
  let minDistance = Infinity;

  pageElements.forEach((pageEl, idx) => {
    const pageNumber = idx + 1;
    const rect = pageEl.getBoundingClientRect();
    const containerRect = container.getBoundingClientRect();
    const pageCenter = rect.top - containerRect.top + rect.height / 2 + scrollTop;
    const distance = Math.abs(pageCenter - scrollCenter);

    if (distance < minDistance) {
      minDistance = distance;
      currentVisiblePage = pageNumber;
    }
  });

  if (currentVisiblePage !== props.currentPage) {
    emit('pageChange', currentVisiblePage);
  }
};

onMounted(() => {
  loadPdf();
  if (containerRef.value) {
    containerRef.value.addEventListener('scroll', handleScroll);
  }
});

watch(
  () => props.url,
  () => {
    loadPdf();
  }
);

watch(
  () => props.zoom,
  () => {
    renderAll();
  }
);

onBeforeUnmount(() => {
  if (containerRef.value) {
    containerRef.value.removeEventListener('scroll', handleScroll);
  }
  if (pdfDoc) {
    try {
      pdfDoc.destroy();
    } catch {
      // ignore
    }
    pdfDoc = null;
  }
});
</script>

<template>
  <div
    ref="containerRef"
    class="vfp-flex vfp-flex-col vfp-items-center vfp-w-full vfp-h-full vfp-overflow-auto vfp-py-4 md:vfp-py-8 vfp-px-2 md:vfp-px-4"
  >
    <div v-if="error" class="vfp-text-white/70 vfp-text-center">
      <p class="vfp-text-lg">{{ error }}</p>
    </div>

    <div v-if="!error && numPages === 0" class="vfp-flex vfp-items-center vfp-justify-center vfp-min-h-screen">
      <div
        class="vfp-w-12 vfp-h-12 vfp-border-4 vfp-border-white/20 vfp-border-t-white vfp-rounded-full vfp-animate-spin"
      />
    </div>

    <div v-show="!error && numPages > 0" class="pdf-pages vfp-flex vfp-flex-col vfp-gap-4" />

    <div
      v-if="numPages > 0"
      class="vfp-sticky vfp-bottom-2 md:vfp-bottom-4 vfp-mt-4 md:vfp-mt-8 vfp-bg-black/60 vfp-backdrop-blur-xl vfp-text-white vfp-px-4 vfp-py-2 md:vfp-px-6 md:vfp-py-3 vfp-rounded-full vfp-text-xs md:vfp-text-sm vfp-font-medium vfp-shadow-2xl vfp-border vfp-border-white/10"
    >
      第 {{ currentPage }} 页 / 共 {{ numPages }} 页
    </div>
  </div>
</template>
