// packages/react-file-preview/src/FilePreviewModal.tsx
import { useEffect } from 'react';
import { createPortal } from 'react-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { PreviewFileInput, CustomRenderer } from './types';
import { FilePreviewContent } from './FilePreviewContent';

interface FilePreviewModalProps {
  files: PreviewFileInput[];
  currentIndex: number;
  isOpen: boolean;
  onClose: () => void;
  onNavigate?: (index: number) => void;
  customRenderers?: CustomRenderer[];
}

export const FilePreviewModal: React.FC<FilePreviewModalProps> = ({
  files,
  currentIndex,
  isOpen,
  onClose,
  onNavigate,
  customRenderers = [],
}) => {
  // 锁定 body 滚动
  useEffect(() => {
    if (isOpen) {
      const originalOverflow = document.body.style.overflow;
      const originalPaddingRight = document.body.style.paddingRight;

      const scrollbarWidth = window.innerWidth - document.documentElement.clientWidth;

      document.body.style.overflow = 'hidden';
      if (scrollbarWidth > 0) {
        document.body.style.paddingRight = `${scrollbarWidth}px`;
      }

      return () => {
        document.body.style.overflow = originalOverflow;
        document.body.style.paddingRight = originalPaddingRight;
      };
    }
  }, [isOpen]);

  if (!isOpen) return null;

  const modalContent = (
    <div className="rfp-root">
      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="rfp-fixed rfp-inset-0 rfp-z-[9999] rfp-flex rfp-items-center rfp-justify-center rfp-bg-black/80 rfp-backdrop-blur-md rfp-overflow-hidden"
            onClick={onClose}
            onWheel={(e) => e.stopPropagation()}
          >
            <div
              className="rfp-relative rfp-w-full rfp-h-full"
              onClick={(e) => e.stopPropagation()}
            >
              <FilePreviewContent
                mode="modal"
                files={files}
                currentIndex={currentIndex}
                onClose={onClose}
                onNavigate={onNavigate}
                customRenderers={customRenderers}
              />
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );

  return createPortal(modalContent, document.body);
};

// packages/vue-file-preview/src/FilePreviewModal.vue
<script setup lang="ts">
import { watch } from 'vue';
import type { PreviewFileInput, Locale, Messages } from '@eternalheart/file-preview-core';
import type { CustomRenderer } from './types';
import FilePreviewContent from './FilePreviewContent.vue';
import { useScrollLock } from './composables/useScrollLock';

interface Props {
  files: PreviewFileInput[];
  currentIndex: number;
  isOpen: boolean;
  customRenderers?: CustomRenderer[];
  /** 语言 */
  locale?: Locale;
  /** 自定义翻译字典 */
  messages?: Partial<Record<Locale, Partial<Messages>>>;
}

const props = withDefaults(defineProps<Props>(), {
  customRenderers: () => [],
  locale: undefined,
  messages: undefined,
});

const emit = defineEmits<{
  (e: 'close'): void;
  (e: 'navigate', index: number): void;
}>();

const { lock, unlock } = useScrollLock(() => props.isOpen);

watch(
  () => props.isOpen,
  (open) => {
    if (open) lock();
    else unlock();
  }
);

const handleBackdropClick = () => emit('close');
const handleContentClick = (e: MouseEvent) => e.stopPropagation();
const handleWheel = (e: WheelEvent) => e.stopPropagation();
</script>

<template>
  <Teleport to="body">
    <Transition name="vfp-fade">
      <div v-if="isOpen" class="vfp-root">
        <div
          class="vfp-fixed vfp-inset-0 vfp-z-[9999] vfp-flex vfp-items-center vfp-justify-center vfp-bg-black/80 vfp-backdrop-blur-md vfp-overflow-hidden"
          @click="handleBackdropClick"
          @wheel="handleWheel"
        >
          <div class="vfp-relative vfp-w-full vfp-h-full" @click="handleContentClick">
            <FilePreviewContent
              mode="modal"
              :files="files"
              :current-index="currentIndex"
              :custom-renderers="customRenderers"
              :locale="locale"
              :messages="messages"
              @close="emit('close')"
              @navigate="(i) => emit('navigate', i)"
            />
          </div>
        </div>
      </div>
    </Transition>
  </Teleport>
</template>
