// packages/react-file-preview/src/FilePreviewEmbed.tsx
import { PreviewFileInput, CustomRenderer } from './types';
import { FilePreviewContent } from './FilePreviewContent';

interface FilePreviewEmbedProps {
  files: PreviewFileInput[];
  currentIndex?: number;
  onNavigate?: (index: number) => void;
  customRenderers?: CustomRenderer[];
  /** 宽度,默认 100% 填充父容器 */
  width?: number | string;
  /** 高度,默认 100% 填充父容器 */
  height?: number | string;
  className?: string;
  style?: React.CSSProperties;
}

export const FilePreviewEmbed: React.FC<FilePreviewEmbedProps> = ({
  files,
  currentIndex = 0,
  onNavigate,
  customRenderers = [],
  width = '100%',
  height = '100%',
  className,
  style,
}) => {
  return (
    <div
      className={`rfp-root ${className ?? ''}`}
      style={{ width, height, ...style }}
    >
      <div className="rfp-relative rfp-w-full rfp-h-full rfp-overflow-hidden rfp-bg-black/80">
        <FilePreviewContent
          mode="embed"
          files={files}
          currentIndex={currentIndex}
          onNavigate={onNavigate}
          customRenderers={customRenderers}
        />
      </div>
    </div>
  );
};

// packages/vue-file-preview/src/FilePreviewEmbed.vue
<script setup lang="ts">
import type { CSSProperties } from 'vue';
import type { PreviewFileInput, Locale, Messages } from '@eternalheart/file-preview-core';
import type { CustomRenderer } from './types';
import FilePreviewContent from './FilePreviewContent.vue';

interface Props {
  files: PreviewFileInput[];
  currentIndex?: number;
  customRenderers?: CustomRenderer[];
  /** 宽度,默认 100% 填充父容器 */
  width?: number | string;
  /** 高度,默认 100% 填充父容器 */
  height?: number | string;
  /** 语言 */
  locale?: Locale;
  /** 自定义翻译字典 */
  messages?: Partial<Record<Locale, Partial<Messages>>>;
}

const props = withDefaults(defineProps<Props>(), {
  currentIndex: 0,
  customRenderers: () => [],
  width: '100%',
  height: '100%',
  locale: undefined,
  messages: undefined,
});

const emit = defineEmits<{
  (e: 'navigate', index: number): void;
}>();

const wrapperStyle: CSSProperties = {
  width: typeof props.width === 'number' ? `${props.width}px` : props.width,
  height: typeof props.height === 'number' ? `${props.height}px` : props.height,
};
</script>

<template>
  <div class="vfp-root" :style="wrapperStyle">
    <div class="vfp-relative vfp-w-full vfp-h-full vfp-overflow-hidden vfp-bg-black/80">
      <FilePreviewContent
        mode="embed"
        :files="files"
        :current-index="currentIndex"
        :custom-renderers="customRenderers"
        :locale="locale"
        :messages="messages"
        @navigate="(i) => emit('navigate', i)"
      />
    </div>
  </div>
</template>
