// packages/react-file-preview/src/FilePreviewContent.tsx
import { useState, useEffect, useCallback, useMemo, useRef } from 'react';
import { motion } from 'framer-motion';
import {
  X,
  ZoomIn,
  ZoomOut,
  RotateCw,
  RotateCcw,
  Download,
  ChevronLeft,
  ChevronRight,
  Scan,
  RefreshCw,
  Maximize2,
  Minimize2,
  List,
} from 'lucide-react';

const OriginalSizeIcon: React.FC<{ className?: string }> = ({ className }) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
    className={className}
  >
    <text x="12" y="17.5" textAnchor="middle" fontSize="20" fontWeight="bold" fill="currentColor" stroke="none">
      1:1
    </text>
  </svg>
);

import { PreviewFile, PreviewFileInput, FileType, CustomRenderer } from './types';
import { normalizeFiles } from './utils/fileNormalizer';
import { ImageRenderer } from './renderers/ImageRenderer';
import { PdfRenderer } from './renderers/PdfRenderer';
import { DocxRenderer } from './renderers/DocxRenderer';
import { XlsxRenderer } from './renderers/XlsxRenderer';
import { PptxRenderer } from './renderers/PptxRenderer';
import { MsgRenderer } from './renderers/MsgRenderer';
import { EpubRenderer } from './renderers/EpubRenderer';
import type { EpubRendererHandle } from './renderers/EpubRenderer';
import { VideoRenderer } from './renderers/VideoRenderer';
import { AudioRenderer } from './renderers/AudioRenderer';
import { MarkdownRenderer } from './renderers/MarkdownRenderer';
import { TextRenderer } from './renderers/TextRenderer';
import { UnsupportedRenderer } from './renderers/UnsupportedRenderer';

export interface FilePreviewContentProps {
  files: PreviewFileInput[];
  currentIndex: number;
  onNavigate?: (index: number) => void;
  customRenderers?: CustomRenderer[];
  /** 运行模式:modal(弹窗) 或 embed(嵌入) */
  mode?: 'modal' | 'embed';
  /** 关闭回调,仅 modal 模式使用 */
  onClose?: () => void;
}

const getFileType = (file: PreviewFile): FileType => {
  const ext = file.name.split('.').pop()?.toLowerCase() || '';
  const mimeType = file.type.toLowerCase();

  if (mimeType.startsWith('image/') || ['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg'].includes(ext)) {
    return 'image';
  }
  if (mimeType.includes('pdf') || ext === 'pdf') {
    return 'pdf';
  }
  if (mimeType.includes('wordprocessingml') || ext === 'docx') {
    return 'docx';
  }
  if (mimeType.includes('spreadsheetml') || ext === 'xlsx') {
    return 'xlsx';
  }
  if (mimeType.includes('presentationml') || ext === 'pptx' || ext === 'ppt') {
    return 'pptx';
  }
  if (mimeType.includes('ms-outlook') || ext === 'msg') {
    return 'msg';
  }
  if (mimeType.includes('epub') || ext === 'epub') {
    return 'epub';
  }
  if (mimeType.startsWith('video/') || ['mp4', 'webm', 'ogg', 'ogv', 'mov', 'avi', 'mkv', 'm4v', '3gp', 'flv'].includes(ext)) {
    return 'video';
  }
  if (mimeType.startsWith('audio/') || ['mp3', 'wav', 'ogg', 'm4a', 'flac', 'aac'].includes(ext)) {
    return 'audio';
  }
  if (ext === 'md' || ext === 'markdown') {
    return 'markdown';
  }
  const textExtensions = [
    'txt', 'log', 'csv',
    'js', 'jsx', 'ts', 'tsx', 'json',
    'py', 'java', 'cpp', 'c', 'h', 'cs', 'php', 'rb', 'go', 'rs', 'swift', 'kt',
    'html', 'css', 'scss', 'sass', 'less',
    'xml', 'yaml', 'yml', 'toml', 'ini', 'conf',
    'sh', 'bash', 'zsh', 'sql',
  ];
  if (mimeType.startsWith('text/') || textExtensions.includes(ext)) {
    return 'text';
  }
  return 'unsupported';
};

export const FilePreviewContent: React.FC<FilePreviewContentProps> = ({
  files,
  currentIndex,
  onNavigate,
  customRenderers = [],
  mode = 'modal',
  onClose,
}) => {
  const [zoom, setZoom] = useState(1);
  const [rotation, setRotation] = useState(0);
  const [currentPage, setCurrentPage] = useState(1);
  const [, setTotalPages] = useState(1);
  const [contentNaturalWidth, setContentNaturalWidth] = useState(0);
  const [contentNaturalHeight, setContentNaturalHeight] = useState(0);
  const [imageResetKey, setImageResetKey] = useState(0);
  const contentRef = useRef<HTMLDivElement>(null);
  const rootRef = useRef<HTMLDivElement>(null);
  const epubRef = useRef<EpubRendererHandle>(null);
  const [epubCurrent, setEpubCurrent] = useState(0);
  const [epubTotal, setEpubTotal] = useState(0);
  const [epubFullWidth, setEpubFullWidth] = useState(false);

  // 导航箭头自动隐藏
  const [navVisible, setNavVisible] = useState(true);
  const navHideTimerRef = useRef<number | null>(null);
  const NAV_HIDE_DELAY = 2000;

  const resetNavTimer = useCallback(() => {
    setNavVisible(true);
    if (navHideTimerRef.current) {
      clearTimeout(navHideTimerRef.current);
    }
    navHideTimerRef.current = window.setTimeout(() => {
      setNavVisible(false);
    }, NAV_HIDE_DELAY);
  }, []);

  const handleMouseMove = useCallback(() => {
    resetNavTimer();
  }, [resetNavTimer]);

  // 标准化文件输入
  const normalizedFiles = useMemo(() => normalizeFiles(files), [files]);

  const currentFile = normalizedFiles[currentIndex];

  // 检查是否有自定义渲染器匹配当前文件
  const customRenderer = useMemo(() => {
    if (!currentFile) return null;
    return customRenderers.find(renderer => renderer.test(currentFile));
  }, [currentFile, customRenderers]);

  const fileType = currentFile ? getFileType(currentFile) : 'unsupported';

  // 重置状态当文件改变时
  useEffect(() => {
    setZoom(1);
    setRotation(0);
    setCurrentPage(1);
    setTotalPages(1);
    setContentNaturalWidth(0);
    setContentNaturalHeight(0);
    setNavVisible(true);
    if (navHideTimerRef.current) {
      clearTimeout(navHideTimerRef.current);
    }
  }, [currentIndex]);

  // 图片加载后默认适应窗口
  useEffect(() => {
    if (fileType === 'image' && contentNaturalWidth > 0 && contentNaturalHeight > 0 && contentRef.current) {
      const containerWidth = contentRef.current.clientWidth;
      const containerHeight = contentRef.current.clientHeight;
      const scaleX = containerWidth / contentNaturalWidth;
      const scaleY = containerHeight / contentNaturalHeight;
      const newZoom = Math.min(scaleX, scaleY);
      setZoom(Math.max(0.01, Math.min(10, newZoom)));
    }
  }, [fileType, contentNaturalWidth, contentNaturalHeight]);

  // 导航箭头自动隐藏计时器启动 & 清理
  useEffect(() => {
    if (normalizedFiles.length > 1) {
      resetNavTimer();
    }
    return () => {
      if (navHideTimerRef.current) {
        clearTimeout(navHideTimerRef.current);
      }
    };
  }, [normalizedFiles.length, resetNavTimer]);

  // 键盘导航
  // - modal 模式:全局监听(window)
  // - embed 模式:只在根容器 focus 时监听,避免影响外部页面交互
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape' && mode === 'modal') {
        onClose?.();
      } else if (e.key === 'ArrowLeft' && currentIndex > 0) {
        onNavigate?.(currentIndex - 1);
      } else if (e.key === 'ArrowRight' && currentIndex < normalizedFiles.length - 1) {
        onNavigate?.(currentIndex + 1);
      }
    };

    if (mode === 'modal') {
      window.addEventListener('keydown', handleKeyDown);
      return () => window.removeEventListener('keydown', handleKeyDown);
    } else {
      const el = rootRef.current;
      if (!el) return;
      el.addEventListener('keydown', handleKeyDown as EventListener);
      return () => el.removeEventListener('keydown', handleKeyDown as EventListener);
    }
  }, [mode, currentIndex, normalizedFiles.length, onClose, onNavigate]);

  const handleZoomIn = useCallback(() => {
    setZoom((prev) => Math.min(prev + 0.1, 10));
  }, []);

  const handleZoomOut = useCallback(() => {
    setZoom((prev) => Math.max(prev - 0.1, 0.01));
  }, []);

  const handleRotate = useCallback(() => {
    setRotation((prev) => prev + 90);
  }, []);

  const handleRotateLeft = useCallback(() => {
    setRotation((prev) => prev - 90);
  }, []);

  const handleFitToWidth = useCallback(() => {
    if (contentRef.current && contentNaturalWidth > 0 && contentNaturalHeight > 0) {
      const containerWidth = contentRef.current.clientWidth;
      const containerHeight = contentRef.current.clientHeight;
      const scaleX = containerWidth / contentNaturalWidth;
      const scaleY = containerHeight / contentNaturalHeight;
      const newZoom = Math.min(scaleX, scaleY);
      setZoom(Math.max(0.01, Math.min(10, newZoom)));
    } else {
      setZoom(1);
    }
    setRotation(0);
    setImageResetKey(k => k + 1);
  }, [contentNaturalWidth, contentNaturalHeight]);

  const handleOriginalSize = useCallback(() => {
    setZoom(1);
    setRotation(0);
    setImageResetKey(k => k + 1);
  }, []);

  const handleZoomChange = useCallback((newZoom: number) => {
    setZoom(newZoom);
  }, []);

  const handleReset = useCallback(() => {
    setZoom(1);
    setRotation(0);
    setImageResetKey(k => k + 1);
  }, []);

  const handleDownload = useCallback(() => {
    if (!currentFile) return;
    const link = document.createElement('a');
    link.href = currentFile.url;
    link.download = currentFile.name;
    link.click();
  }, [currentFile]);

  const handleEpubChapterChange = useCallback((current: number, total: number) => {
    setEpubCurrent(current);
    setEpubTotal(total);
  }, []);

  if (!currentFile) return null;

  const showZoomControls = fileType === 'image' || fileType === 'pdf';
  const showRotateControl = fileType === 'image';
  const showEpubControls = fileType === 'epub';
  const showCloseButton = mode === 'modal' && !!onClose;

  return (
    <div
      ref={rootRef}
      tabIndex={mode === 'embed' ? 0 : -1}
      className="rfp-relative rfp-w-full rfp-h-full rfp-flex rfp-flex-col rfp-overflow-hidden rfp-outline-none"
    >
      {/* 顶部工具栏 - 全屏融合式 */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        className="rfp-flex-shrink-0 rfp-z-10 rfp-bg-black/50 rfp-backdrop-blur-md rfp-border-b rfp-border-white/10"
        style={{ paddingTop: 'env(safe-area-inset-top, 0px)' }}
      >
        {/* 第一行:文件名 + 分页 + 关闭/下载(移动端右侧)/ 全部按钮(桌面端) */}
        <div className="rfp-flex rfp-items-center rfp-justify-between rfp-px-3 md:rfp-px-5 rfp-py-1.5 md:rfp-py-2.5">
          {/* 左侧:文件名 + 分页 */}
          <div className="rfp-flex rfp-items-center rfp-flex-1 rfp-min-w-0 rfp-mr-2 md:rfp-mr-3">
            <h2 className="rfp-text-white/90 rfp-font-medium rfp-text-xs md:rfp-text-sm rfp-truncate">
              {currentFile.name}
            </h2>
            <span className="rfp-text-white/40 rfp-text-xs rfp-ml-2 rfp-flex-shrink-0">
              {currentIndex + 1}/{normalizedFiles.length}
            </span>
          </div>

          {/* 移动端:仅显示下载+关闭 */}
          <div className="rfp-flex rfp-items-center rfp-gap-1 md:rfp-hidden rfp-flex-shrink-0">
            <ToolbarButton
              icon={<Download className="rfp-w-4 rfp-h-4" />}
              label="下载"
              onClick={handleDownload}
            />
            {showCloseButton && (
              <ToolbarButton
                icon={<X className="rfp-w-4 rfp-h-4" />}
                label="关闭"
                onClick={onClose!}
              />
            )}
          </div>

          {/* 桌面端:所有工具按钮 */}
          <div className="rfp-hidden md:rfp-flex rfp-items-center rfp-gap-1 rfp-flex-shrink-0">
            {showZoomControls && (
              <>
                <ToolbarButton
                  icon={<ZoomOut className="rfp-w-4 rfp-h-4" />}
                  label="缩小"
                  onClick={handleZoomOut}
                  disabled={zoom <= 0.01}
                />
                <span className="rfp-text-white/60 rfp-text-xs rfp-min-w-[3rem] rfp-text-center rfp-font-medium rfp-tabular-nums">
                  {Math.round(zoom * 100)}%
                </span>
                <ToolbarButton
                  icon={<ZoomIn className="rfp-w-4 rfp-h-4" />}
                  label="放大"
                  onClick={handleZoomIn}
                  disabled={zoom >= 10}
                />
                <div className="rfp-w-px rfp-h-4 rfp-bg-white/10 rfp-mx-1" />
                {fileType === 'image' && (
                  <>
                    <ToolbarButton
                      icon={<Scan className="rfp-w-4 rfp-h-4" />}
                      label="适应窗口"
                      onClick={handleFitToWidth}
                    />
                    <ToolbarButton
                      icon={<OriginalSizeIcon className="rfp-w-4 rfp-h-4" />}
                      label="原始尺寸"
                      onClick={handleOriginalSize}
                    />
                    <div className="rfp-w-px rfp-h-4 rfp-bg-white/10 rfp-mx-1" />
                  </>
                )}
              </>
            )}

            {showRotateControl && (
              <>
                <ToolbarButton
                  icon={<RotateCcw className="rfp-w-4 rfp-h-4" />}
                  label="向左旋转"
                  onClick={handleRotateLeft}
                />
                <ToolbarButton
                  icon={<RotateCw className="rfp-w-4 rfp-h-4" />}
                  label="向右旋转"
                  onClick={handleRotate}
                />
                <div className="rfp-w-px rfp-h-4 rfp-bg-white/10 rfp-mx-1" />
              </>
            )}

            {(showZoomControls || showRotateControl) && (
              <>
                <ToolbarButton
                  icon={<RefreshCw className="rfp-w-4 rfp-h-4" />}
                  label="复原"
                  onClick={handleReset}
                />
                <div className="rfp-w-px rfp-h-4 rfp-bg-white/10 rfp-mx-1" />
              </>
            )}

            {showEpubControls && (
              <>
                <ToolbarButton
                  icon={<List className="rfp-w-4 rfp-h-4" />}
                  label="目录"
                  onClick={() => epubRef.current?.toggleToc()}
                />
                <div className="rfp-w-px rfp-h-4 rfp-bg-white/10 rfp-mx-1" />
                <ToolbarButton
                  icon={<ChevronLeft className="rfp-w-4 rfp-h-4" />}
                  label="上一章"
                  onClick={() => epubRef.current?.prevChapter()}
                />
                <span className="rfp-text-white/60 rfp-text-xs rfp-min-w-[4rem] rfp-text-center rfp-font-medium rfp-tabular-nums">
                  {epubCurrent} / {epubTotal}
                </span>
                <ToolbarButton
                  icon={<ChevronRight className="rfp-w-4 rfp-h-4" />}
                  label="下一章"
                  onClick={() => epubRef.current?.nextChapter()}
                />
                <div className="rfp-w-px rfp-h-4 rfp-bg-white/10 rfp-mx-1" />
                <ToolbarButton
                  icon={epubFullWidth ? <Minimize2 className="rfp-w-4 rfp-h-4" /> : <Maximize2 className="rfp-w-4 rfp-h-4" />}
                  label={epubFullWidth ? '正常宽度' : '全屏宽度'}
                  onClick={() => epubRef.current?.toggleFullWidth()}
                />
                <div className="rfp-w-px rfp-h-4 rfp-bg-white/10 rfp-mx-1" />
              </>
            )}

            <ToolbarButton
              icon={<Download className="rfp-w-4 rfp-h-4" />}
              label="下载"
              onClick={handleDownload}
            />
            {showCloseButton && (
              <ToolbarButton
                icon={<X className="rfp-w-4 rfp-h-4" />}
                label="关闭"
                onClick={onClose!}
              />
            )}
          </div>
        </div>

        {/* 第二行:移动端工具按钮(image/pdf/epub) */}
        {(showZoomControls || showRotateControl || showEpubControls) && (
          <div className="rfp-flex rfp-items-center rfp-gap-1 rfp-px-3 rfp-pb-1.5 rfp-overflow-x-auto scrollbar-hide md:rfp-hidden">
            {showZoomControls && (
              <>
                <ToolbarButton
                  icon={<ZoomOut className="rfp-w-4 rfp-h-4" />}
                  label="缩小"
                  onClick={handleZoomOut}
                  disabled={zoom <= 0.01}
                />
                <span className="rfp-text-white/60 rfp-text-xs rfp-min-w-[3rem] rfp-text-center rfp-font-medium rfp-tabular-nums">
                  {Math.round(zoom * 100)}%
                </span>
                <ToolbarButton
                  icon={<ZoomIn className="rfp-w-4 rfp-h-4" />}
                  label="放大"
                  onClick={handleZoomIn}
                  disabled={zoom >= 10}
                />
                <div className="rfp-w-px rfp-h-4 rfp-bg-white/10 rfp-mx-0.5" />
                {fileType === 'image' && (
                  <>
                    <ToolbarButton
                      icon={<Scan className="rfp-w-4 rfp-h-4" />}
                      label="适应窗口"
                      onClick={handleFitToWidth}
                    />
                    <ToolbarButton
                      icon={<OriginalSizeIcon className="rfp-w-4 rfp-h-4" />}
                      label="原始尺寸"
                      onClick={handleOriginalSize}
                    />
                    <div className="rfp-w-px rfp-h-4 rfp-bg-white/10 rfp-mx-0.5" />
                  </>
                )}
              </>
            )}

            {showRotateControl && (
              <>
                <ToolbarButton
                  icon={<RotateCcw className="rfp-w-4 rfp-h-4" />}
                  label="向左旋转"
                  onClick={handleRotateLeft}
                />
                <ToolbarButton
                  icon={<RotateCw className="rfp-w-4 rfp-h-4" />}
                  label="向右旋转"
                  onClick={handleRotate}
                />
                <div className="rfp-w-px rfp-h-4 rfp-bg-white/10 rfp-mx-0.5" />
              </>
            )}

            <ToolbarButton
              icon={<RefreshCw className="rfp-w-4 rfp-h-4" />}
              label="复原"
              onClick={handleReset}
            />

            {showEpubControls && (
              <>
                <div className="rfp-w-px rfp-h-4 rfp-bg-white/10 rfp-mx-0.5" />
                <ToolbarButton
                  icon={<List className="rfp-w-4 rfp-h-4" />}
                  label="目录"
                  onClick={() => epubRef.current?.toggleToc()}
                />
                <ToolbarButton
                  icon={<ChevronLeft className="rfp-w-4 rfp-h-4" />}
                  label="上一章"
                  onClick={() => epubRef.current?.prevChapter()}
                />
                <span className="rfp-text-white/60 rfp-text-xs rfp-min-w-[4rem] rfp-text-center rfp-font-medium rfp-tabular-nums">
                  {epubCurrent} / {epubTotal}
                </span>
                <ToolbarButton
                  icon={<ChevronRight className="rfp-w-4 rfp-h-4" />}
                  label="下一章"
                  onClick={() => epubRef.current?.nextChapter()}
                />
                <ToolbarButton
                  icon={epubFullWidth ? <Minimize2 className="rfp-w-4 rfp-h-4" /> : <Maximize2 className="rfp-w-4 rfp-h-4" />}
                  label={epubFullWidth ? '正常宽度' : '全屏宽度'}
                  onClick={() => epubRef.current?.toggleFullWidth()}
                />
              </>
            )}
          </div>
        )}
      </motion.div>

      {/* 内容区域 */}
      <div
        ref={contentRef}
        className="rfp-flex-1 rfp-flex rfp-items-center rfp-justify-center rfp-overflow-auto"
        onMouseMove={handleMouseMove}
      >
        {customRenderer ? (
          customRenderer.render(currentFile)
        ) : (
          <>
            {fileType === 'image' && (
              <ImageRenderer
                url={currentFile.url}
                zoom={zoom}
                rotation={rotation}
                resetKey={imageResetKey}
                fileSize={currentFile.size}
                onZoomChange={handleZoomChange}
                onNaturalWidthChange={setContentNaturalWidth}
                onNaturalHeightChange={setContentNaturalHeight}
              />
            )}
            {fileType === 'pdf' && (
              <PdfRenderer
                url={currentFile.url}
                zoom={zoom}
                currentPage={currentPage}
                onPageChange={setCurrentPage}
                onTotalPagesChange={setTotalPages}
                onPageWidthChange={setContentNaturalWidth}
              />
            )}
            {fileType === 'docx' && <DocxRenderer url={currentFile.url} />}
            {fileType === 'xlsx' && <XlsxRenderer url={currentFile.url} />}
            {fileType === 'pptx' && <PptxRenderer url={currentFile.url} />}
            {fileType === 'msg' && <MsgRenderer url={currentFile.url} />}
            {fileType === 'epub' && (
              <EpubRenderer
                ref={epubRef}
                url={currentFile.url}
                onChapterChange={handleEpubChapterChange}
                onFullWidthChange={setEpubFullWidth}
              />
            )}
            {fileType === 'video' && <VideoRenderer url={currentFile.url} />}
            {fileType === 'audio' && (
              <AudioRenderer url={currentFile.url} fileName={currentFile.name} />
            )}
            {fileType === 'markdown' && <MarkdownRenderer url={currentFile.url} />}
            {fileType === 'text' && (
              <TextRenderer url={currentFile.url} fileName={currentFile.name} />
            )}
            {fileType === 'unsupported' && (
              <UnsupportedRenderer
                fileName={currentFile.name}
                fileType={currentFile.type}
                onDownload={handleDownload}
              />
            )}
          </>
        )}
      </div>

      {/* 左右导航箭头 - 自动隐藏 */}
      {normalizedFiles.length > 1 && (
        <>
          {currentIndex > 0 && (
            <motion.button
              initial={{ opacity: 0 }}
              animate={{ opacity: navVisible ? 1 : 0, x: navVisible ? 0 : -20 }}
              transition={{ duration: 0.2 }}
              onClick={() => onNavigate?.(currentIndex - 1)}
              onMouseEnter={() => setNavVisible(true)}
              style={{ pointerEvents: navVisible ? 'auto' : 'none' }}
              className="rfp-absolute rfp-z-20 rfp-left-2 md:rfp-left-4 rfp-top-1/2 -rfp-translate-y-1/2 rfp-w-10 rfp-h-10 md:rfp-w-12 md:rfp-h-12 rfp-rounded-full rfp-bg-black/40 rfp-backdrop-blur-xl rfp-border rfp-border-white/10 rfp-flex rfp-items-center rfp-justify-center rfp-text-white hover:rfp-bg-black/60 rfp-transition-colors rfp-shadow-2xl"
            >
              <ChevronLeft className="rfp-w-5 rfp-h-5 md:rfp-w-6 md:rfp-h-6" />
            </motion.button>
          )}

          {currentIndex < normalizedFiles.length - 1 && (
            <motion.button
              initial={{ opacity: 0 }}
              animate={{ opacity: navVisible ? 1 : 0, x: navVisible ? 0 : 20 }}
              transition={{ duration: 0.2 }}
              onClick={() => onNavigate?.(currentIndex + 1)}
              onMouseEnter={() => setNavVisible(true)}
              style={{ pointerEvents: navVisible ? 'auto' : 'none' }}
              className="rfp-absolute rfp-z-20 rfp-right-2 md:rfp-right-4 rfp-top-1/2 -rfp-translate-y-1/2 rfp-w-10 rfp-h-10 md:rfp-w-12 md:rfp-h-12 rfp-rounded-full rfp-bg-black/40 rfp-backdrop-blur-xl rfp-border rfp-border-white/10 rfp-flex rfp-items-center rfp-justify-center rfp-text-white hover:rfp-bg-black/60 rfp-transition-colors rfp-shadow-2xl"
            >
              <ChevronRight className="rfp-w-5 rfp-h-5 md:rfp-w-6 md:rfp-h-6" />
            </motion.button>
          )}
        </>
      )}
    </div>
  );
};

// 工具栏按钮组件
interface ToolbarButtonProps {
  icon: React.ReactNode;
  label: string;
  onClick: () => void;
  disabled?: boolean;
}

const ToolbarButton: React.FC<ToolbarButtonProps> = ({ icon, label, onClick, disabled }) => {
  return (
    <button
      onClick={onClick}
      disabled={disabled}
      title={label}
      className={`rfp-p-2 md:rfp-p-1.5 rfp-rounded-md rfp-transition-all rfp-select-none ${disabled
        ? 'rfp-text-white/30 rfp-cursor-not-allowed'
        : 'rfp-text-white hover:rfp-bg-white/10 active:rfp-bg-white/20'
        }`}
    >
      {icon}
    </button>
  );
};

// packages/vue-file-preview/src/FilePreviewContent.vue
<script setup lang="ts">
import { ref, computed, watch, onMounted, onBeforeUnmount } from 'vue';
import {
  X,
  ZoomIn,
  ZoomOut,
  RotateCw,
  RotateCcw,
  Download,
  ChevronLeft,
  ChevronRight,
  Scan,
  RefreshCw,
  Maximize2,
  Minimize2,
  List,
} from 'lucide-vue-next';
import {
  normalizeFiles,
  getFileType,
  type PreviewFileInput,
} from '@eternalheart/file-preview-core';
import type { CustomRenderer } from './types';
import ImageRenderer from './renderers/ImageRenderer.vue';
import PdfRenderer from './renderers/PdfRenderer.vue';
import DocxRenderer from './renderers/DocxRenderer.vue';
import XlsxRenderer from './renderers/XlsxRenderer.vue';
import PptxRenderer from './renderers/PptxRenderer.vue';
import MsgRenderer from './renderers/MsgRenderer.vue';
import EpubRenderer from './renderers/EpubRenderer.vue';
import VideoRenderer from './renderers/VideoRenderer.vue';
import AudioRenderer from './renderers/AudioRenderer.vue';
import MarkdownRenderer from './renderers/MarkdownRenderer.vue';
import TextRenderer from './renderers/TextRenderer.vue';
import UnsupportedRenderer from './renderers/UnsupportedRenderer.vue';

interface Props {
  files: PreviewFileInput[];
  currentIndex: number;
  customRenderers?: CustomRenderer[];
  /** 运行模式: modal(弹窗) 或 embed(嵌入) */
  mode?: 'modal' | 'embed';
}

const props = withDefaults(defineProps<Props>(), {
  customRenderers: () => [],
  mode: 'modal',
});

const emit = defineEmits<{
  (e: 'navigate', index: number): void;
  (e: 'close'): void;
}>();

const zoom = ref(1);
const rotation = ref(0);
const currentPage = ref(1);
const totalPages = ref(1);
const contentNaturalWidth = ref(0);
const contentNaturalHeight = ref(0);
const imageResetKey = ref(0);

const contentRef = ref<HTMLDivElement | null>(null);
const rootRef = ref<HTMLDivElement | null>(null);

// 导航箭头自动隐藏
const navVisible = ref(true);
let navHideTimer: number | null = null;
const NAV_HIDE_DELAY = 2000;

const resetNavTimer = () => {
  navVisible.value = true;
  if (navHideTimer !== null) {
    clearTimeout(navHideTimer);
  }
  navHideTimer = window.setTimeout(() => {
    navVisible.value = false;
  }, NAV_HIDE_DELAY);
};

const handleMouseMove = () => resetNavTimer();

// 标准化文件输入
const normalizedFiles = computed(() => normalizeFiles(props.files));

const currentFile = computed(() => normalizedFiles.value[props.currentIndex]);

// 自定义渲染器匹配
const customRenderer = computed(() => {
  if (!currentFile.value) return null;
  return props.customRenderers.find((r) => r.test(currentFile.value!)) || null;
});

const customRendererComponent = computed(() => {
  if (!customRenderer.value || !currentFile.value) return null;
  return customRenderer.value.render(currentFile.value);
});

const fileType = computed(() => (currentFile.value ? getFileType(currentFile.value) : 'unsupported'));

// 重置状态当文件改变时
watch(
  () => props.currentIndex,
  () => {
    zoom.value = 1;
    rotation.value = 0;
    currentPage.value = 1;
    totalPages.value = 1;
    contentNaturalWidth.value = 0;
    contentNaturalHeight.value = 0;
    navVisible.value = true;
    if (navHideTimer !== null) {
      clearTimeout(navHideTimer);
    }
  }
);

// 图片加载后默认适应窗口
watch(
  [fileType, contentNaturalWidth, contentNaturalHeight],
  () => {
    if (
      fileType.value === 'image' &&
      contentNaturalWidth.value > 0 &&
      contentNaturalHeight.value > 0 &&
      contentRef.value
    ) {
      const containerWidth = contentRef.value.clientWidth;
      const containerHeight = contentRef.value.clientHeight;
      const scaleX = containerWidth / contentNaturalWidth.value;
      const scaleY = containerHeight / contentNaturalHeight.value;
      const newZoom = Math.min(scaleX, scaleY);
      zoom.value = Math.max(0.01, Math.min(10, newZoom));
    }
  }
);

// 导航箭头自动隐藏计时器
watch(
  () => normalizedFiles.value.length,
  (len) => {
    if (len > 1) resetNavTimer();
  },
  { immediate: true }
);

// 键盘导航
const handleKeyDown = (e: KeyboardEvent) => {
  if (e.key === 'Escape' && props.mode === 'modal') {
    emit('close');
  } else if (e.key === 'ArrowLeft' && props.currentIndex > 0) {
    emit('navigate', props.currentIndex - 1);
  } else if (e.key === 'ArrowRight' && props.currentIndex < normalizedFiles.value.length - 1) {
    emit('navigate', props.currentIndex + 1);
  }
};

onMounted(() => {
  if (props.mode === 'modal') {
    window.addEventListener('keydown', handleKeyDown);
  } else if (rootRef.value) {
    rootRef.value.addEventListener('keydown', handleKeyDown as EventListener);
  }
});

onBeforeUnmount(() => {
  if (navHideTimer !== null) clearTimeout(navHideTimer);
  if (props.mode === 'modal') {
    window.removeEventListener('keydown', handleKeyDown);
  } else if (rootRef.value) {
    rootRef.value.removeEventListener('keydown', handleKeyDown as EventListener);
  }
});

const handleZoomIn = () => {
  zoom.value = Math.min(zoom.value + 0.1, 10);
};
const handleZoomOut = () => {
  zoom.value = Math.max(zoom.value - 0.1, 0.01);
};
const handleRotate = () => {
  rotation.value = rotation.value + 90;
};
const handleRotateLeft = () => {
  rotation.value = rotation.value - 90;
};

const handleFitToWidth = () => {
  if (contentRef.value && contentNaturalWidth.value > 0 && contentNaturalHeight.value > 0) {
    const containerWidth = contentRef.value.clientWidth;
    const containerHeight = contentRef.value.clientHeight;
    const scaleX = containerWidth / contentNaturalWidth.value;
    const scaleY = containerHeight / contentNaturalHeight.value;
    const newZoom = Math.min(scaleX, scaleY);
    zoom.value = Math.max(0.01, Math.min(10, newZoom));
  } else {
    zoom.value = 1;
  }
  rotation.value = 0;
  imageResetKey.value++;
};

const handleOriginalSize = () => {
  zoom.value = 1;
  rotation.value = 0;
  imageResetKey.value++;
};

const handleZoomChange = (newZoom: number) => {
  zoom.value = newZoom;
};

const handleReset = () => {
  zoom.value = 1;
  rotation.value = 0;
  imageResetKey.value++;
};

const handleDownload = () => {
  if (!currentFile.value) return;
  const link = document.createElement('a');
  link.href = currentFile.value.url;
  link.download = currentFile.value.name;
  link.click();
};

const showZoomControls = computed(() => fileType.value === 'image' || fileType.value === 'pdf');
const showRotateControl = computed(() => fileType.value === 'image');
const showEpubControls = computed(() => fileType.value === 'epub');
const showCloseButton = computed(() => props.mode === 'modal');

const epubRef = ref<{ prevChapter: () => void; nextChapter: () => void; toggleFullWidth: () => void; toggleToc: () => void } | null>(null);
const epubCurrent = ref(0);
const epubTotal = ref(0);
const epubFullWidth = ref(false);

const handleEpubChapterChange = (current: number, total: number) => {
  epubCurrent.value = current;
  epubTotal.value = total;
};
</script>

<template>
  <div
    ref="rootRef"
    :tabindex="mode === 'embed' ? 0 : -1"
    class="vfp-relative vfp-w-full vfp-h-full vfp-flex vfp-flex-col vfp-overflow-hidden vfp-outline-none"
  >
    <!-- 顶部工具栏 -->
    <div
      class="vfp-flex-shrink-0 vfp-z-10 vfp-bg-black/50 vfp-backdrop-blur-md vfp-border-b vfp-border-white/10"
      style="padding-top: env(safe-area-inset-top, 0px)"
    >
      <!-- 第一行: 文件名 + 桌面端工具按钮 -->
      <div class="vfp-flex vfp-items-center vfp-justify-between vfp-px-3 md:vfp-px-5 vfp-py-1.5 md:vfp-py-2.5">
        <!-- 左侧: 文件名 + 分页 -->
        <div class="vfp-flex vfp-items-center vfp-flex-1 vfp-min-w-0 vfp-mr-2 md:vfp-mr-3">
          <h2 class="vfp-text-white/90 vfp-font-medium vfp-text-xs md:vfp-text-sm vfp-truncate">
            {{ currentFile?.name }}
          </h2>
          <span class="vfp-text-white/40 vfp-text-xs vfp-ml-2 vfp-flex-shrink-0">
            {{ currentIndex + 1 }}/{{ normalizedFiles.length }}
          </span>
        </div>

        <!-- 移动端: 仅下载 + 关闭 -->
        <div class="vfp-flex vfp-items-center vfp-gap-1 md:vfp-hidden vfp-flex-shrink-0">
          <button class="toolbar-btn" title="下载" @click="handleDownload">
            <Download class="vfp-w-4 vfp-h-4" />
          </button>
          <button v-if="showCloseButton" class="toolbar-btn" title="关闭" @click="emit('close')">
            <X class="vfp-w-4 vfp-h-4" />
          </button>
        </div>

        <!-- 桌面端: 完整工具按钮 -->
        <div class="vfp-hidden md:vfp-flex vfp-items-center vfp-gap-1 vfp-flex-shrink-0">
          <template v-if="showZoomControls">
            <button class="toolbar-btn" :disabled="zoom <= 0.01" title="缩小" @click="handleZoomOut">
              <ZoomOut class="vfp-w-4 vfp-h-4" />
            </button>
            <span
              class="vfp-text-white/60 vfp-text-xs vfp-min-w-[3rem] vfp-text-center vfp-font-medium vfp-tabular-nums"
            >
              {{ Math.round(zoom * 100) }}%
            </span>
            <button class="toolbar-btn" :disabled="zoom >= 10" title="放大" @click="handleZoomIn">
              <ZoomIn class="vfp-w-4 vfp-h-4" />
            </button>
            <div class="vfp-w-px vfp-h-4 vfp-bg-white/10 vfp-mx-1" />

            <template v-if="fileType === 'image'">
              <button class="toolbar-btn" title="适应窗口" @click="handleFitToWidth">
                <Scan class="vfp-w-4 vfp-h-4" />
              </button>
              <button class="toolbar-btn" title="原始尺寸" @click="handleOriginalSize">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  stroke-width="2"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  class="vfp-w-4 vfp-h-4"
                >
                  <text
                    x="12"
                    y="17.5"
                    text-anchor="middle"
                    font-size="20"
                    font-weight="bold"
                    fill="currentColor"
                    stroke="none"
                  >
                    1:1
                  </text>
                </svg>
              </button>
              <div class="vfp-w-px vfp-h-4 vfp-bg-white/10 vfp-mx-1" />
            </template>
          </template>

          <template v-if="showRotateControl">
            <button class="toolbar-btn" title="向左旋转" @click="handleRotateLeft">
              <RotateCcw class="vfp-w-4 vfp-h-4" />
            </button>
            <button class="toolbar-btn" title="向右旋转" @click="handleRotate">
              <RotateCw class="vfp-w-4 vfp-h-4" />
            </button>
            <div class="vfp-w-px vfp-h-4 vfp-bg-white/10 vfp-mx-1" />
          </template>

          <template v-if="showZoomControls || showRotateControl">
            <button class="toolbar-btn" title="复原" @click="handleReset">
              <RefreshCw class="vfp-w-4 vfp-h-4" />
            </button>
            <div class="vfp-w-px vfp-h-4 vfp-bg-white/10 vfp-mx-1" />
          </template>

          <template v-if="showEpubControls">
            <button class="toolbar-btn" title="目录" @click="epubRef?.toggleToc()">
              <List class="vfp-w-4 vfp-h-4" />
            </button>
            <div class="vfp-w-px vfp-h-4 vfp-bg-white/10 vfp-mx-1" />
            <button class="toolbar-btn" title="上一章" @click="epubRef?.prevChapter()">
              <ChevronLeft class="vfp-w-4 vfp-h-4" />
            </button>
            <span
              class="vfp-text-white/60 vfp-text-xs vfp-min-w-[4rem] vfp-text-center vfp-font-medium vfp-tabular-nums"
            >
              {{ epubCurrent }} / {{ epubTotal }}
            </span>
            <button class="toolbar-btn" title="下一章" @click="epubRef?.nextChapter()">
              <ChevronRight class="vfp-w-4 vfp-h-4" />
            </button>
            <div class="vfp-w-px vfp-h-4 vfp-bg-white/10 vfp-mx-1" />
            <button class="toolbar-btn" :title="epubFullWidth ? '正常宽度' : '全屏宽度'" @click="epubRef?.toggleFullWidth()">
              <Minimize2 v-if="epubFullWidth" class="vfp-w-4 vfp-h-4" />
              <Maximize2 v-else class="vfp-w-4 vfp-h-4" />
            </button>
            <div class="vfp-w-px vfp-h-4 vfp-bg-white/10 vfp-mx-1" />
          </template>

          <button class="toolbar-btn" title="下载" @click="handleDownload">
            <Download class="vfp-w-4 vfp-h-4" />
          </button>
          <button v-if="showCloseButton" class="toolbar-btn" title="关闭" @click="emit('close')">
            <X class="vfp-w-4 vfp-h-4" />
          </button>
        </div>
      </div>

      <!-- 移动端第二行工具按钮 -->
      <div
        v-if="showZoomControls || showRotateControl || showEpubControls"
        class="vfp-flex vfp-items-center vfp-gap-1 vfp-px-3 vfp-pb-1.5 vfp-overflow-x-auto scrollbar-hide md:vfp-hidden"
      >
        <template v-if="showZoomControls">
          <button class="toolbar-btn" :disabled="zoom <= 0.01" title="缩小" @click="handleZoomOut">
            <ZoomOut class="vfp-w-4 vfp-h-4" />
          </button>
          <span
            class="vfp-text-white/60 vfp-text-xs vfp-min-w-[3rem] vfp-text-center vfp-font-medium vfp-tabular-nums"
          >
            {{ Math.round(zoom * 100) }}%
          </span>
          <button class="toolbar-btn" :disabled="zoom >= 10" title="放大" @click="handleZoomIn">
            <ZoomIn class="vfp-w-4 vfp-h-4" />
          </button>
          <div class="vfp-w-px vfp-h-4 vfp-bg-white/10 vfp-mx-0.5" />
          <template v-if="fileType === 'image'">
            <button class="toolbar-btn" title="适应窗口" @click="handleFitToWidth">
              <Scan class="vfp-w-4 vfp-h-4" />
            </button>
            <button class="toolbar-btn" title="原始尺寸" @click="handleOriginalSize">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="vfp-w-4 vfp-h-4"
              >
                <text
                  x="12"
                  y="17.5"
                  text-anchor="middle"
                  font-size="20"
                  font-weight="bold"
                  fill="currentColor"
                  stroke="none"
                >
                  1:1
                </text>
              </svg>
            </button>
            <div class="vfp-w-px vfp-h-4 vfp-bg-white/10 vfp-mx-0.5" />
          </template>
        </template>

        <template v-if="showRotateControl">
          <button class="toolbar-btn" title="向左旋转" @click="handleRotateLeft">
            <RotateCcw class="vfp-w-4 vfp-h-4" />
          </button>
          <button class="toolbar-btn" title="向右旋转" @click="handleRotate">
            <RotateCw class="vfp-w-4 vfp-h-4" />
          </button>
          <div class="vfp-w-px vfp-h-4 vfp-bg-white/10 vfp-mx-0.5" />
        </template>

        <button class="toolbar-btn" title="复原" @click="handleReset">
          <RefreshCw class="vfp-w-4 vfp-h-4" />
        </button>

        <template v-if="showEpubControls">
          <div class="vfp-w-px vfp-h-4 vfp-bg-white/10 vfp-mx-0.5" />
          <button class="toolbar-btn" title="目录" @click="epubRef?.toggleToc()">
            <List class="vfp-w-4 vfp-h-4" />
          </button>
          <button class="toolbar-btn" title="上一章" @click="epubRef?.prevChapter()">
            <ChevronLeft class="vfp-w-4 vfp-h-4" />
          </button>
          <span
            class="vfp-text-white/60 vfp-text-xs vfp-min-w-[4rem] vfp-text-center vfp-font-medium vfp-tabular-nums"
          >
            {{ epubCurrent }} / {{ epubTotal }}
          </span>
          <button class="toolbar-btn" title="下一章" @click="epubRef?.nextChapter()">
            <ChevronRight class="vfp-w-4 vfp-h-4" />
          </button>
          <button class="toolbar-btn" :title="epubFullWidth ? '正常宽度' : '全屏宽度'" @click="epubRef?.toggleFullWidth()">
            <Minimize2 v-if="epubFullWidth" class="vfp-w-4 vfp-h-4" />
            <Maximize2 v-else class="vfp-w-4 vfp-h-4" />
          </button>
        </template>
      </div>
    </div>

    <!-- 内容区域 -->
    <div
      ref="contentRef"
      class="vfp-flex-1 vfp-flex vfp-items-center vfp-justify-center vfp-overflow-auto"
      @mousemove="handleMouseMove"
    >
      <template v-if="currentFile">
        <component :is="customRendererComponent" v-if="customRendererComponent" :file="currentFile" />
        <template v-else>
          <ImageRenderer
            v-if="fileType === 'image'"
            :url="currentFile.url"
            :zoom="zoom"
            :rotation="rotation"
            :reset-key="imageResetKey"
            :file-size="currentFile.size"
            @zoom-change="handleZoomChange"
            @natural-width-change="(w: number) => (contentNaturalWidth = w)"
            @natural-height-change="(h: number) => (contentNaturalHeight = h)"
          />
          <PdfRenderer
            v-else-if="fileType === 'pdf'"
            :url="currentFile.url"
            :zoom="zoom"
            :current-page="currentPage"
            @page-change="(p: number) => (currentPage = p)"
            @total-pages-change="(t: number) => (totalPages = t)"
            @page-width-change="(w: number) => (contentNaturalWidth = w)"
          />
          <DocxRenderer v-else-if="fileType === 'docx'" :url="currentFile.url" />
          <XlsxRenderer v-else-if="fileType === 'xlsx'" :url="currentFile.url" />
          <PptxRenderer v-else-if="fileType === 'pptx'" :url="currentFile.url" />
          <MsgRenderer v-else-if="fileType === 'msg'" :url="currentFile.url" />
          <EpubRenderer
            v-else-if="fileType === 'epub'"
            ref="epubRef"
            :url="currentFile.url"
            @chapter-change="handleEpubChapterChange"
            @full-width-change="(v: boolean) => (epubFullWidth = v)"
          />
          <VideoRenderer v-else-if="fileType === 'video'" :url="currentFile.url" />
          <AudioRenderer
            v-else-if="fileType === 'audio'"
            :url="currentFile.url"
            :file-name="currentFile.name"
          />
          <MarkdownRenderer v-else-if="fileType === 'markdown'" :url="currentFile.url" />
          <TextRenderer
            v-else-if="fileType === 'text'"
            :url="currentFile.url"
            :file-name="currentFile.name"
          />
          <UnsupportedRenderer
            v-else
            :file-name="currentFile.name"
            :file-type="currentFile.type"
            @download="handleDownload"
          />
        </template>
      </template>
    </div>

    <!-- 左右导航箭头 -->
    <template v-if="normalizedFiles.length > 1">
      <button
        v-if="currentIndex > 0"
        :style="{
          opacity: navVisible ? 1 : 0,
          transform: navVisible ? 'translateY(-50%)' : 'translateY(-50%) translateX(-20px)',
          pointerEvents: navVisible ? 'auto' : 'none',
          transition: 'opacity 0.2s, transform 0.2s',
        }"
        class="vfp-absolute vfp-z-20 vfp-left-2 md:vfp-left-4 vfp-top-1/2 vfp-w-10 vfp-h-10 md:vfp-w-12 md:vfp-h-12 vfp-rounded-full vfp-bg-black/40 vfp-backdrop-blur-xl vfp-border vfp-border-white/10 vfp-flex vfp-items-center vfp-justify-center vfp-text-white hover:vfp-bg-black/60 vfp-transition-colors vfp-shadow-2xl"
        @click="emit('navigate', currentIndex - 1)"
        @mouseenter="navVisible = true"
      >
        <ChevronLeft class="vfp-w-5 vfp-h-5 md:vfp-w-6 md:vfp-h-6" />
      </button>

      <button
        v-if="currentIndex < normalizedFiles.length - 1"
        :style="{
          opacity: navVisible ? 1 : 0,
          transform: navVisible ? 'translateY(-50%)' : 'translateY(-50%) translateX(20px)',
          pointerEvents: navVisible ? 'auto' : 'none',
          transition: 'opacity 0.2s, transform 0.2s',
        }"
        class="vfp-absolute vfp-z-20 vfp-right-2 md:vfp-right-4 vfp-top-1/2 vfp-w-10 vfp-h-10 md:vfp-w-12 md:vfp-h-12 vfp-rounded-full vfp-bg-black/40 vfp-backdrop-blur-xl vfp-border vfp-border-white/10 vfp-flex vfp-items-center vfp-justify-center vfp-text-white hover:vfp-bg-black/60 vfp-transition-colors vfp-shadow-2xl"
        @click="emit('navigate', currentIndex + 1)"
        @mouseenter="navVisible = true"
      >
        <ChevronRight class="vfp-w-5 vfp-h-5 md:vfp-w-6 md:vfp-h-6" />
      </button>
    </template>
  </div>
</template>

<style scoped>
.toolbar-btn {
  padding: 0.5rem;
  border-radius: 0.375rem;
  transition: all 0.15s;
  user-select: none;
  color: white;
  background: transparent;
  border: 0;
  cursor: pointer;
}
@media (min-width: 768px) {
  .toolbar-btn {
    padding: 0.375rem;
  }
}
.toolbar-btn:hover {
  background: rgba(255, 255, 255, 0.1);
}
.toolbar-btn:active {
  background: rgba(255, 255, 255, 0.2);
}
.toolbar-btn:disabled {
  color: rgba(255, 255, 255, 0.3);
  cursor: not-allowed;
}
</style>
