// packages/vue-file-preview/src/renderers/Json/index.vue
<script setup lang="ts">
import { ref, watch } from 'vue';
import { fetchTextUtf8 } from '@eternalheart/file-preview-core';

const props = defineProps<{
  url: string;
  fileName: string;
}>();

const data = ref<unknown>(null);
const loading = ref(true);
const error = ref<string | null>(null);

const loadJson = async () => {
  loading.value = true;
  error.value = null;
  try {
    const text = await fetchTextUtf8(props.url);
    data.value = JSON.parse(text);
  } catch (err) {
    console.error(err);
    error.value = 'JSON 文件加载失败';
  } finally {
    loading.value = false;
  }
};

watch(() => props.url, loadJson, { immediate: true });
</script>

<template>
  <div v-if="loading" class="vfp-flex vfp-items-center vfp-justify-center vfp-w-full vfp-h-full">
    <div class="vfp-w-12 vfp-h-12 vfp-border-4 vfp-border-white/20 vfp-border-t-white vfp-rounded-full vfp-animate-spin" />
  </div>

  <div v-else-if="error" class="vfp-flex vfp-items-center vfp-justify-center vfp-w-full vfp-h-full">
    <div class="vfp-text-white/70 vfp-text-center">
      <p class="vfp-text-lg">{{ error }}</p>
    </div>
  </div>

  <div v-else class="vfp-w-full vfp-h-full vfp-overflow-auto vfp-py-3 vfp-pr-4" style="background: #1e1e1e;">
    <JsonNode :value="data" :depth="0" :default-expanded="true" />
  </div>
</template>

<!-- 递归 JSON 节点组件 -->
<script lang="ts">
import { defineComponent, h, type PropType } from 'vue';
import { ChevronRight, ChevronDown } from 'lucide-vue-next';

export default defineComponent({ name: 'JsonRenderer' });

function renderValue(value: unknown) {
  if (value === null) return h('span', { class: 'json-null' }, 'null');
  if (value === undefined) return h('span', { class: 'json-null' }, 'undefined');
  if (typeof value === 'boolean') return h('span', { class: 'json-bool' }, String(value));
  if (typeof value === 'number') return h('span', { class: 'json-number' }, String(value));
  if (typeof value === 'string') return h('span', { class: 'json-string' }, `"${value}"`);
  return h('span', { class: 'json-bracket' }, String(value));
}

function renderPrimitiveLine(keyName: string | undefined, value: unknown, indent: number, override?: string) {
  return h('div', { class: 'json-row', style: { paddingLeft: `${indent}px` } }, [
    h('span', { class: 'json-arrow-placeholder' }),
    keyName !== undefined
      ? h('span', { class: 'json-key' }, [
          `"${keyName}"`,
          h('span', { class: 'json-colon' }, ': '),
        ])
      : null,
    override
      ? h('span', { class: 'json-bracket' }, override)
      : renderValue(value),
  ]);
}

const JsonNode = defineComponent({
  name: 'JsonNode',
  props: {
    keyName: { type: String, default: undefined },
    value: { type: null as unknown as PropType<unknown>, required: true },
    depth: { type: Number, required: true },
    defaultExpanded: { type: Boolean, default: false },
  },
  setup(props) {
    const expanded = ref(props.defaultExpanded);
    const toggle = () => { expanded.value = !expanded.value; };
    return { expanded, toggle };
  },
  render() {
    const { keyName, value, depth, expanded, toggle } = this;
    const indent = depth * 20;

    // 基本类型
    if (value === null || value === undefined || typeof value !== 'object') {
      return renderPrimitiveLine(keyName, value, indent);
    }

    const isArr = Array.isArray(value);
    const entries = isArr ? (value as unknown[]) : Object.entries(value as Record<string, unknown>);
    const count = entries.length;
    const open = isArr ? '[' : '{';
    const close = isArr ? ']' : '}';

    // 空对象/数组
    if (count === 0) {
      return renderPrimitiveLine(keyName, null, indent, `${open}${close}`);
    }

    const children = [];

    // 折叠行
    children.push(
      h('div', {
        class: 'json-row json-toggle',
        style: { paddingLeft: `${indent}px` },
        onClick: toggle,
      }, [
        h('span', { class: 'json-arrow' }, [
          h(expanded ? ChevronDown : ChevronRight, { class: 'vfp-w-3.5 vfp-h-3.5' }),
        ]),
        keyName !== undefined
          ? h('span', { class: 'json-key' }, [
              `"${keyName}"`,
              h('span', { class: 'json-colon' }, ': '),
            ])
          : null,
        h('span', { class: 'json-bracket' }, open),
        !expanded
          ? h('span', { class: 'json-collapsed' }, [
              isArr ? `${count} items` : `${count} keys`,
              h('span', { class: 'json-bracket' }, ` ${close}`),
            ])
          : null,
      ])
    );

    // 子节点
    if (expanded) {
      if (isArr) {
        (value as unknown[]).forEach((item, i) => {
          children.push(
            h(JsonNode, { key: i, value: item, depth: depth + 1, defaultExpanded: depth < 1 })
          );
        });
      } else {
        Object.entries(value as Record<string, unknown>).forEach(([k, v]) => {
          children.push(
            h(JsonNode, { key: k, keyName: k, value: v, depth: depth + 1, defaultExpanded: depth < 1 })
          );
        });
      }
      children.push(
        h('div', { class: 'json-row', style: { paddingLeft: `${indent + 20}px` } }, [
          h('span', { class: 'json-bracket' }, close),
        ])
      );
    }

    return h('div', null, children);
  },
});
</script>

<style scoped>
.json-row {
  display: flex;
  align-items: flex-start;
  padding-top: 1px;
  padding-bottom: 1px;
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
  font-size: 0.875rem;
  line-height: 1.4;
}
.json-toggle {
  cursor: pointer;
  user-select: none;
}
.json-toggle:hover {
  background: rgba(255, 255, 255, 0.05);
}
.json-arrow {
  width: 16px;
  height: 20px;
  flex-shrink: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  color: rgba(255, 255, 255, 0.4);
}
.json-arrow-placeholder {
  width: 16px;
  height: 20px;
  flex-shrink: 0;
}
.json-key {
  color: #9cdcfe;
  flex-shrink: 0;
}
.json-colon {
  color: rgba(255, 255, 255, 0.5);
}
.json-bracket {
  color: rgba(255, 255, 255, 0.7);
}
.json-collapsed {
  color: rgba(255, 255, 255, 0.3);
  margin-left: 4px;
}
.json-string {
  color: #ce9178;
}
.json-number {
  color: #b5cea8;
}
.json-bool,
.json-null {
  color: #569cd6;
}
.json-null {
  font-style: italic;
}
</style>

// packages/react-file-preview/src/renderers/Json/index.tsx
import { useState, useEffect, useCallback } from 'react';
import { ChevronRight, ChevronDown } from 'lucide-react';
import { fetchTextUtf8 } from '@eternalheart/file-preview-core';

interface JsonRendererProps {
  url: string;
  fileName: string;
}

// ---------- JSON 树节点 ----------

interface JsonNodeProps {
  keyName?: string;
  value: unknown;
  depth: number;
  defaultExpanded: boolean;
}

const JsonNode: React.FC<JsonNodeProps> = ({ keyName, value, depth, defaultExpanded }) => {
  const [expanded, setExpanded] = useState(defaultExpanded);
  const indent = depth * 20;

  const toggle = useCallback(() => setExpanded(prev => !prev), []);

  // 基本类型
  if (value === null || value === undefined || typeof value !== 'object') {
    return (
      <div className="rfp-flex rfp-items-start rfp-py-px rfp-font-mono rfp-text-sm" style={{ paddingLeft: `${indent}px` }}>
        <span className="rfp-w-4 rfp-h-5 rfp-flex-shrink-0" />
        {keyName !== undefined && (
          <span className="rfp-text-[#9cdcfe] rfp-flex-shrink-0">
            "{keyName}"<span className="rfp-text-white/50">: </span>
          </span>
        )}
        {renderPrimitive(value)}
      </div>
    );
  }

  const isArray = Array.isArray(value);
  const entries = isArray ? (value as unknown[]) : Object.entries(value as Record<string, unknown>);
  const count = entries.length;
  const openBracket = isArray ? '[' : '{';
  const closeBracket = isArray ? ']' : '}';

  // 空对象/数组
  if (count === 0) {
    return (
      <div className="rfp-flex rfp-items-start rfp-py-px rfp-font-mono rfp-text-sm" style={{ paddingLeft: `${indent}px` }}>
        <span className="rfp-w-4 rfp-h-5 rfp-flex-shrink-0" />
        {keyName !== undefined && (
          <span className="rfp-text-[#9cdcfe] rfp-flex-shrink-0">
            "{keyName}"<span className="rfp-text-white/50">: </span>
          </span>
        )}
        <span className="rfp-text-white/70">{openBracket}{closeBracket}</span>
      </div>
    );
  }

  return (
    <div>
      {/* 折叠行 */}
      <div
        className="rfp-flex rfp-items-start rfp-py-px rfp-font-mono rfp-text-sm rfp-cursor-pointer hover:rfp-bg-white/5 rfp-select-none"
        style={{ paddingLeft: `${indent}px` }}
        onClick={toggle}
      >
        <span className="rfp-w-4 rfp-h-5 rfp-flex-shrink-0 rfp-flex rfp-items-center rfp-justify-center rfp-text-white/40">
          {expanded
            ? <ChevronDown className="rfp-w-3.5 rfp-h-3.5" />
            : <ChevronRight className="rfp-w-3.5 rfp-h-3.5" />
          }
        </span>
        {keyName !== undefined && (
          <span className="rfp-text-[#9cdcfe] rfp-flex-shrink-0">
            "{keyName}"<span className="rfp-text-white/50">: </span>
          </span>
        )}
        <span className="rfp-text-white/70">{openBracket}</span>
        {!expanded && (
          <span className="rfp-text-white/30 rfp-ml-1">
            {isArray ? `${count} items` : `${count} keys`}
            <span className="rfp-text-white/70"> {closeBracket}</span>
          </span>
        )}
      </div>

      {/* 子节点 */}
      {expanded && (
        <>
          {isArray
            ? (value as unknown[]).map((item, i) => (
                <JsonNode key={i} value={item} depth={depth + 1} defaultExpanded={depth < 1} />
              ))
            : Object.entries(value as Record<string, unknown>).map(([k, v]) => (
                <JsonNode key={k} keyName={k} value={v} depth={depth + 1} defaultExpanded={depth < 1} />
              ))
          }
          <div className="rfp-font-mono rfp-text-sm rfp-text-white/70 rfp-py-px" style={{ paddingLeft: `${indent + 20}px` }}>
            {closeBracket}
          </div>
        </>
      )}
    </div>
  );
};

function renderPrimitive(value: unknown) {
  if (value === null) return <span className="rfp-text-[#569cd6] rfp-italic">null</span>;
  if (value === undefined) return <span className="rfp-text-[#569cd6] rfp-italic">undefined</span>;
  if (typeof value === 'boolean') return <span className="rfp-text-[#569cd6]">{String(value)}</span>;
  if (typeof value === 'number') return <span className="rfp-text-[#b5cea8]">{String(value)}</span>;
  if (typeof value === 'string') return <span className="rfp-text-[#ce9178]">"{value}"</span>;
  return <span className="rfp-text-white/70">{String(value)}</span>;
}

// ---------- Main ----------

export const JsonRenderer: React.FC<JsonRendererProps> = ({ url }) => {
  const [data, setData] = useState<unknown>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const loadJson = async () => {
      try {
        setLoading(true);
        setError(null);
        const text = await fetchTextUtf8(url);
        setData(JSON.parse(text));
      } catch (err) {
        setError('JSON 文件加载失败');
        console.error(err);
      } finally {
        setLoading(false);
      }
    };
    loadJson();
  }, [url]);

  if (loading) {
    return (
      <div className="rfp-flex rfp-items-center rfp-justify-center rfp-w-full rfp-h-full">
        <div className="rfp-w-12 rfp-h-12 rfp-border-4 rfp-border-white/20 rfp-border-t-white rfp-rounded-full rfp-animate-spin" />
      </div>
    );
  }

  if (error) {
    return (
      <div className="rfp-flex rfp-items-center rfp-justify-center rfp-w-full rfp-h-full">
        <div className="rfp-text-white/70 rfp-text-center">
          <p className="rfp-text-lg">{error}</p>
        </div>
      </div>
    );
  }

  return (
    <div className="rfp-w-full rfp-h-full rfp-overflow-auto rfp-bg-[#1e1e1e] rfp-py-3 rfp-pr-4">
      <JsonNode value={data} depth={0} defaultExpanded />
    </div>
  );
};
