// packages/vue-file-preview/src/renderers/Subtitle/index.vue
<script setup lang="ts">
import { ref, computed, watch } from 'vue';
import {
  parseSubtitle,
  formatSubtitleTime,
  fetchTextUtf8,
  type SubtitleParseResult,
  type SubtitleFormat,
} from '@eternalheart/file-preview-core';

const props = defineProps<{
  url: string;
  fileName: string;
}>();

const text = ref<string>('');
const loading = ref(true);
const error = ref<string | null>(null);

const FORMAT_BY_EXT: Record<string, SubtitleFormat> = {
  srt: 'srt',
  vtt: 'vtt',
  lrc: 'lrc',
  elrc: 'elrc',
  ass: 'ass',
  ssa: 'ssa',
  ttml: 'ttml',
  dfxp: 'ttml',
};

const getFormat = (fileName: string): SubtitleFormat | undefined => {
  const ext = fileName.split('.').pop()?.toLowerCase() || '';
  return FORMAT_BY_EXT[ext];
};

const load = async () => {
  loading.value = true;
  error.value = null;
  try {
    text.value = await fetchTextUtf8(props.url);
  } catch (err) {
    console.error(err);
    error.value = '字幕文件加载失败';
  } finally {
    loading.value = false;
  }
};

watch(() => props.url, load, { immediate: true });

const parsed = computed<SubtitleParseResult | null>(() => {
  if (!text.value) return null;
  try {
    return parseSubtitle(text.value, getFormat(props.fileName));
  } catch (err) {
    console.error(err);
    return null;
  }
});

const isLyric = computed(() => parsed.value?.format === 'lrc' || parsed.value?.format === 'elrc');

const meta = computed<Record<string, string>>(() => parsed.value?.metadata ?? {});

const wordTimeShort = (t: number) => formatSubtitleTime(t).slice(3, 8);
</script>

<template>
  <div
    v-if="loading"
    class="vfp-flex vfp-items-center vfp-justify-center vfp-w-full vfp-h-full vfp-bg-[#0f0f12]"
  >
    <div
      class="vfp-w-12 vfp-h-12 vfp-border-4 vfp-border-white/20 vfp-border-t-white vfp-rounded-full vfp-animate-spin"
    />
  </div>

  <div
    v-else-if="error || !parsed"
    class="vfp-flex vfp-items-center vfp-justify-center vfp-w-full vfp-h-full vfp-bg-[#0f0f12]"
  >
    <div class="vfp-text-white/70 vfp-text-center">
      <p class="vfp-text-lg">{{ error || '字幕解析失败' }}</p>
    </div>
  </div>

  <div
    v-else
    class="vfp-relative vfp-w-full vfp-h-full vfp-bg-[#0f0f12]"
    :class="isLyric ? 'flavor-lyric' : 'flavor-subtitle'"
  >
    <!-- 内容滚动区 -->
    <div class="content-scroll">
      <div class="timeline">
        <div class="timeline-line" />
        <ol class="cues">
          <li v-for="(cue, i) in parsed.cues" :key="'cue-' + i" class="cue-row">
            <div class="cue-dot" />
            <div class="cue-meta">
              <span class="cue-time">{{ formatSubtitleTime(cue.start) }}</span>
              <span class="cue-arrow">→</span>
              <span class="cue-time">{{ formatSubtitleTime(cue.end) }}</span>
              <span class="cue-id">#{{ cue.id ?? i + 1 }}</span>
              <span v-if="cue.style" class="cue-style">{{ cue.style }}</span>
            </div>
            <div v-if="cue.words && cue.words.length > 0" class="cue-words">
              <span
                v-for="(word, wi) in cue.words"
                :key="'w-' + wi"
                class="cue-word"
                :title="formatSubtitleTime(word.start)"
              >
                <span class="cue-word-time">{{ wordTimeShort(word.start) }}</span>
                <span class="cue-word-text">{{ word.text }}</span>
              </span>
            </div>
            <p v-else class="cue-text" :class="{ lyric: isLyric }">{{ cue.text }}</p>
          </li>
        </ol>
      </div>
    </div>

    <!-- 右下角浮签 -->
    <div class="status-pill">
      <span>{{ parsed.cues.length }} {{ isLyric ? 'lines' : 'cues' }}</span>
      <template v-if="meta.length">
        <span class="dot">·</span>
        <span>{{ meta.length }}</span>
      </template>
    </div>
  </div>
</template>

<style scoped>
.content-scroll {
  width: 100%;
  height: 100%;
  overflow: auto;
  padding: 1.5rem 1.5rem 4rem;
}
@media (min-width: 768px) {
  .content-scroll {
    padding: 1.5rem 2.5rem 5rem;
  }
}
.status-pill {
  pointer-events: none;
  position: absolute;
  bottom: 0.75rem;
  right: 0.75rem;
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.25rem 0.625rem;
  border-radius: 9999px;
  background: rgba(0, 0, 0, 0.4);
  backdrop-filter: blur(8px);
  border: 1px solid rgba(255, 255, 255, 0.1);
  font-size: 0.625rem;
  color: rgba(255, 255, 255, 0.55);
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
  font-variant-numeric: tabular-nums;
}
@media (min-width: 768px) {
  .status-pill {
    bottom: 1rem;
    right: 1rem;
  }
}
.dot {
  color: rgba(255, 255, 255, 0.2);
}

.timeline {
  position: relative;
  max-width: 64rem;
  margin: 0 auto;
}
.timeline-line {
  position: absolute;
  left: 5px;
  top: 0.5rem;
  bottom: 0.5rem;
  width: 1px;
  background: rgba(255, 255, 255, 0.08);
}
@media (min-width: 768px) {
  .timeline-line {
    left: 7px;
  }
}
.cues {
  list-style: none;
  margin: 0;
  padding: 0;
  display: flex;
  flex-direction: column;
  gap: 1.25rem;
}
@media (min-width: 768px) {
  .cues {
    gap: 1.5rem;
  }
}
.cue-row {
  position: relative;
  padding-left: 1.5rem;
}
@media (min-width: 768px) {
  .cue-row {
    padding-left: 2rem;
  }
}
.cue-dot {
  position: absolute;
  left: 0;
  top: 0.5rem;
  width: 0.75rem;
  height: 0.75rem;
  border-radius: 9999px;
  background: rgba(255, 255, 255, 0.15);
  border: 2px solid #0f0f12;
  transition: background-color 0.2s;
}
.flavor-lyric .cue-row:hover .cue-dot {
  background: rgb(167, 139, 250);
}
.flavor-subtitle .cue-row:hover .cue-dot {
  background: rgb(56, 189, 248);
}
.cue-meta {
  display: flex;
  flex-wrap: wrap;
  align-items: baseline;
  gap: 0.25rem 0.75rem;
  margin-bottom: 0.375rem;
}
.cue-time {
  font-size: 0.6875rem;
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
  color: rgba(255, 255, 255, 0.45);
  font-variant-numeric: tabular-nums;
}
.cue-arrow {
  font-size: 0.6875rem;
  color: rgba(255, 255, 255, 0.25);
}
.cue-id {
  font-size: 0.625rem;
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
  color: rgba(255, 255, 255, 0.25);
  font-variant-numeric: tabular-nums;
}
.cue-style {
  font-size: 0.5625rem;
  text-transform: uppercase;
  letter-spacing: 0.1em;
  color: rgba(255, 255, 255, 0.55);
  padding: 0.125rem 0.375rem;
  border-radius: 0.25rem;
  background: rgba(255, 255, 255, 0.06);
  border: 1px solid rgba(255, 255, 255, 0.1);
}
.cue-text {
  margin: 0;
  white-space: pre-wrap;
  word-break: break-word;
  line-height: 1.625;
  color: rgba(255, 255, 255, 0.9);
  font-size: 0.875rem;
  transition: color 0.2s;
}
@media (min-width: 768px) {
  .cue-text {
    font-size: 1rem;
  }
}
.cue-text.lyric {
  font-size: 1rem;
  font-weight: 500;
}
@media (min-width: 768px) {
  .cue-text.lyric {
    font-size: 1.25rem;
  }
}
.cue-row:hover .cue-text {
  color: #fff;
}
.cue-words {
  display: flex;
  flex-wrap: wrap;
  gap: 0.25rem 0.375rem;
  font-size: 1rem;
  color: rgba(255, 255, 255, 0.9);
  line-height: 1.625;
  transition: color 0.2s;
}
@media (min-width: 768px) {
  .cue-words {
    font-size: 1.125rem;
  }
}
.cue-row:hover .cue-words {
  color: #fff;
}
.cue-word {
  display: inline-flex;
  flex-direction: column;
  align-items: flex-start;
}
.cue-word-time {
  font-size: 0.5625rem;
  color: rgba(255, 255, 255, 0.3);
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
  line-height: 1;
  font-variant-numeric: tabular-nums;
}
.cue-word-text {
  line-height: 1.4;
}
</style>

// packages/react-file-preview/src/renderers/Subtitle/index.tsx
import { useState, useEffect, useMemo } from 'react';
import {
  parseSubtitle,
  formatSubtitleTime,
  fetchTextUtf8,
  type SubtitleParseResult,
  type SubtitleFormat,
} from '@eternalheart/file-preview-core';

interface SubtitleRendererProps {
  url: string;
  fileName: string;
}

const FORMAT_BY_EXT: Record<string, SubtitleFormat> = {
  srt: 'srt',
  vtt: 'vtt',
  lrc: 'lrc',
  elrc: 'elrc',
  ass: 'ass',
  ssa: 'ssa',
  ttml: 'ttml',
  dfxp: 'ttml',
};

const getFormat = (fileName: string): SubtitleFormat | undefined => {
  const ext = fileName.split('.').pop()?.toLowerCase() || '';
  return FORMAT_BY_EXT[ext];
};

export const SubtitleRenderer: React.FC<SubtitleRendererProps> = ({ url, fileName }) => {
  const [text, setText] = useState<string>('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const load = async () => {
      try {
        setLoading(true);
        setError(null);
        setText(await fetchTextUtf8(url));
      } catch (err) {
        console.error(err);
        setError('字幕文件加载失败');
      } finally {
        setLoading(false);
      }
    };
    load();
  }, [url]);

  const parsed: SubtitleParseResult | null = useMemo(() => {
    if (!text) return null;
    try {
      return parseSubtitle(text, getFormat(fileName));
    } catch (err) {
      console.error(err);
      return null;
    }
  }, [text, fileName]);

  if (loading) {
    return (
      <div className="rfp-flex rfp-items-center rfp-justify-center rfp-w-full rfp-h-full rfp-bg-[#0f0f12]">
        <div className="rfp-w-12 rfp-h-12 rfp-border-4 rfp-border-white/20 rfp-border-t-white rfp-rounded-full rfp-animate-spin" />
      </div>
    );
  }

  if (error || !parsed) {
    return (
      <div className="rfp-flex rfp-items-center rfp-justify-center rfp-w-full rfp-h-full rfp-bg-[#0f0f12]">
        <div className="rfp-text-white/70 rfp-text-center">
          <p className="rfp-text-lg">{error || '字幕解析失败'}</p>
        </div>
      </div>
    );
  }

  const isLyric = parsed.format === 'lrc' || parsed.format === 'elrc';
  const meta = parsed.metadata ?? {};
  const dotHover = isLyric ? 'group-hover:rfp-bg-violet-400' : 'group-hover:rfp-bg-sky-400';

  return (
    <div className="rfp-relative rfp-w-full rfp-h-full rfp-bg-[#0f0f12]">
      {/* 内容滚动区 */}
      <div className="rfp-w-full rfp-h-full rfp-overflow-auto rfp-px-6 md:rfp-px-10 rfp-pt-6 rfp-pb-16 md:rfp-pb-20">
        <div className="rfp-relative rfp-max-w-5xl rfp-mx-auto">
          {/* vertical line */}
          <div className="rfp-absolute rfp-left-[5px] md:rfp-left-[7px] rfp-top-2 rfp-bottom-2 rfp-w-px rfp-bg-white/[0.08]" />

          <ol className="rfp-space-y-5 md:rfp-space-y-6">
            {parsed.cues.map((cue, i) => (
              <li key={`cue-${i}`} className="rfp-relative rfp-pl-6 md:rfp-pl-8 rfp-group">
                {/* dot */}
                <div
                  className={`rfp-absolute rfp-left-0 rfp-top-2 rfp-w-3 rfp-h-3 rfp-rounded-full rfp-bg-white/15 rfp-border-2 rfp-border-[#0f0f12] rfp-transition-colors ${dotHover}`}
                />

                <div className="rfp-flex rfp-flex-wrap rfp-items-baseline rfp-gap-x-3 rfp-gap-y-1 rfp-mb-1.5">
                  <span className="rfp-text-[11px] rfp-font-mono rfp-text-white/45 rfp-tabular-nums">
                    {formatSubtitleTime(cue.start)}
                  </span>
                  <span className="rfp-text-[11px] rfp-text-white/25">→</span>
                  <span className="rfp-text-[11px] rfp-font-mono rfp-text-white/45 rfp-tabular-nums">
                    {formatSubtitleTime(cue.end)}
                  </span>
                  <span className="rfp-text-[10px] rfp-font-mono rfp-text-white/25 rfp-tabular-nums">
                    #{cue.id ?? i + 1}
                  </span>
                  {cue.style && (
                    <span className="rfp-text-[9px] rfp-uppercase rfp-tracking-widest rfp-text-white/55 rfp-px-1.5 rfp-py-0.5 rfp-rounded rfp-bg-white/[0.06] rfp-border rfp-border-white/10">
                      {cue.style}
                    </span>
                  )}
                </div>

                {cue.words && cue.words.length > 0 ? (
                  <div className="rfp-flex rfp-flex-wrap rfp-gap-x-1.5 rfp-gap-y-1 rfp-text-base md:rfp-text-lg rfp-text-white/90 rfp-leading-relaxed group-hover:rfp-text-white rfp-transition-colors">
                    {cue.words.map((word, wi) => (
                      <span
                        key={`w-${wi}`}
                        className="rfp-inline-flex rfp-flex-col rfp-items-start"
                        title={formatSubtitleTime(word.start)}
                      >
                        <span className="rfp-text-[9px] rfp-text-white/30 rfp-font-mono rfp-leading-none rfp-tabular-nums">
                          {formatSubtitleTime(word.start).slice(3, 8)}
                        </span>
                        <span className="rfp-leading-snug">{word.text}</span>
                      </span>
                    ))}
                  </div>
                ) : (
                  <p
                    className={`rfp-whitespace-pre-wrap rfp-break-words rfp-leading-relaxed group-hover:rfp-text-white rfp-transition-colors rfp-text-white/90 ${
                      isLyric ? 'rfp-text-base md:rfp-text-xl rfp-font-medium' : 'rfp-text-sm md:rfp-text-base'
                    }`}
                  >
                    {cue.text}
                  </p>
                )}
              </li>
            ))}
          </ol>
        </div>
      </div>

      {/* 底部状态栏 */}
      <div className="rfp-pointer-events-none rfp-absolute rfp-bottom-3 rfp-right-3 md:rfp-bottom-4 md:rfp-right-4 rfp-flex rfp-items-center rfp-gap-2 rfp-px-2.5 rfp-py-1 rfp-rounded-full rfp-bg-black/40 rfp-backdrop-blur rfp-border rfp-border-white/10 rfp-text-[10px] rfp-text-white/55 rfp-font-mono rfp-tabular-nums">
        <span>{parsed.cues.length} {isLyric ? 'lines' : 'cues'}</span>
        {meta.length && (
          <>
            <span className="rfp-text-white/20">·</span>
            <span>{meta.length}</span>
          </>
        )}
      </div>
    </div>
  );
};
