// packages/example/src/App.tsx
import { useState, useRef } from 'react';
import { FilePreviewModal, FilePreviewEmbed, VERSION } from '@eternalheart/react-file-preview';
import type { PreviewFile, PreviewFileInput } from '@eternalheart/react-file-preview';
import '@eternalheart/react-file-preview/style.css';
import { FileText, Image, FileSpreadsheet, Video, Music, Upload, X, Package, BookOpen, Code } from 'lucide-react';
import iconSvg from './assets/icon.svg';

// 环境检测：开发环境和生产环境的 URL
const isDev = import.meta.env.DEV;
const DOCS_URL = isDev
  ? 'http://localhost:4801/file-preview/docs/'
  : 'https://wh131462.github.io/file-preview/docs/';
const VUE_EXAMPLE_URL = isDev
  ? 'http://localhost:4802/'
  : 'https://wh131462.github.io/file-preview/vue/';

function App() {
  const [isPreviewOpen, setIsPreviewOpen] = useState(false);
  const [currentFileIndex, setCurrentFileIndex] = useState(0);
  const [embedIndex, setEmbedIndex] = useState(0);
  const [uploadedFiles, setUploadedFiles] = useState<PreviewFile[]>([]);
  const [allFiles, setAllFiles] = useState<PreviewFileInput[]>([]);
  const [isDragging, setIsDragging] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleFileClick = (index: number) => {
    setCurrentFileIndex(index);
    setIsPreviewOpen(true);
  };

  const getFileIcon = (type: string) => {
    if (type.startsWith('image/')) return <Image className="w-8 h-8" />;
    if (type.includes('pdf')) return <FileText className="w-8 h-8" />;
    if (type.includes('spreadsheet')) return <FileSpreadsheet className="w-8 h-8" />;
    if (type.startsWith('video/')) return <Video className="w-8 h-8" />;
    if (type.startsWith('audio/')) return <Music className="w-8 h-8" />;
    return <FileText className="w-8 h-8" />;
  };

  const processFiles = (files: FileList | null) => {
    if (!files || files.length === 0) return;

    const newFiles: PreviewFile[] = Array.from(files).map((file, index) => ({
      id: `uploaded-${Date.now()}-${index}`,
      name: file.name,
      url: URL.createObjectURL(file),
      type: file.type || 'application/octet-stream',
      size: file.size,
    }));

    setUploadedFiles((prev) => [...prev, ...newFiles]);
    setAllFiles((prev) => [...prev, ...newFiles]);
  };

  const handleFileUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
    const files = event.target.files;
    processFiles(files);

    // 清空 input 以允许重复上传同一文件
    if (fileInputRef.current) {
      fileInputRef.current.value = '';
    }
  };

  const handleDragEnter = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    e.stopPropagation();
    setIsDragging(true);
  };

  const handleDragLeave = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    e.stopPropagation();
    // 只有当离开整个拖拽区域时才设置为 false
    if (e.currentTarget === e.target) {
      setIsDragging(false);
    }
  };

  const handleDragOver = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    e.stopPropagation();
  };

  const handleDrop = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    e.stopPropagation();
    setIsDragging(false);

    const files = e.dataTransfer.files;
    processFiles(files);
  };

  const handleRemoveFile = (fileId: string) => {
    setUploadedFiles((prev) => {
      const fileToRemove = prev.find((f) => f.id === fileId);
      if (fileToRemove) {
        // 释放 blob URL
        URL.revokeObjectURL(fileToRemove.url);
      }
      return prev.filter((f) => f.id !== fileId);
    });
    setAllFiles((prev) => prev.filter((f) => {
      if (typeof f === 'string') return true;
      if (f instanceof File) return true;
      return f.id !== fileId;
    }));
  };

  const formatFileSize = (bytes?: number) => {
    if (!bytes) return '';
    if (bytes < 1024) return `${bytes} B`;
    if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
    return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-900 via-gray-800 to-gray-900">
      {/* 导航栏 */}
      <nav className="bg-black/20 backdrop-blur-xl border-b border-white/10 sticky top-0 z-40">
        <div className="container mx-auto px-3 py-3 sm:px-4 sm:py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2 sm:gap-3 min-w-0">
              <img src={iconSvg} alt="logo" className="w-8 h-8 sm:w-10 sm:h-10 rounded-xl flex-shrink-0" />
              <div className="flex flex-col items-start min-w-0">
                <h1 className="text-base sm:text-xl font-bold text-white truncate">React File Preview</h1>
                <p className="text-[10px] sm:text-xs text-gray-400 truncate max-w-[160px] sm:max-w-none">
                  @eternalheart/react-file-preview@{VERSION}
                </p>
              </div>
            </div>

            <div className="flex items-center gap-1.5 sm:gap-3 flex-shrink-0">
              {/* 框架切换器 */}
              <div className="flex items-center gap-0.5 p-0.5 rounded-lg bg-white/5 border border-white/10">
                <span className="px-2.5 py-1.5 sm:px-3 sm:py-1.5 rounded-md text-xs sm:text-sm font-medium bg-gradient-to-r from-blue-500 to-purple-600 text-white shadow-md">
                  React
                </span>
                <a
                  href={VUE_EXAMPLE_URL}
                  className="px-2.5 py-1.5 sm:px-3 sm:py-1.5 rounded-md text-xs sm:text-sm font-medium text-gray-400 hover:text-white hover:bg-white/5 transition-all"
                  title="切换到 Vue 版本"
                >
                  Vue
                </a>
              </div>

              <a
                href="https://github.com/wh131462/file-preview"
                target="_blank"
                rel="noopener noreferrer"
                className="hidden sm:flex items-center gap-2 px-2.5 py-2 sm:px-4 sm:py-2 rounded-lg bg-white/5 hover:bg-white/10 active:bg-white/15 text-white transition-all hover:scale-105"
              >
                <Code className="w-4 h-4 sm:w-5 sm:h-5" />
                <span className="hidden sm:inline">GitHub</span>
              </a>
              <a
                href="https://www.npmjs.com/package/@eternalheart/react-file-preview"
                target="_blank"
                rel="noopener noreferrer"
                className="hidden sm:flex items-center gap-2 px-2.5 py-2 sm:px-4 sm:py-2 rounded-lg bg-white/5 hover:bg-white/10 active:bg-white/15 text-white transition-all hover:scale-105"
              >
                <Package className="w-4 h-4 sm:w-5 sm:h-5" />
                <span className="hidden sm:inline">npm</span>
              </a>
              <a
                href={DOCS_URL}
                target="_blank"
                rel="noopener noreferrer"
                className="hidden sm:flex items-center gap-2 px-2.5 py-2 sm:px-4 sm:py-2 rounded-lg bg-gradient-to-r from-blue-500 to-purple-600 text-white transition-all hover:scale-105 hover:shadow-lg active:scale-95"
              >
                <BookOpen className="w-4 h-4 sm:w-5 sm:h-5" />
                <span className="hidden sm:inline">API Docs</span>
              </a>
            </div>
          </div>
        </div>
      </nav>

      <div className="container mx-auto px-3 sm:px-4 py-8 sm:py-16">
        <div className="text-center mb-8 sm:mb-12">
          <h2 className="text-2xl sm:text-4xl font-bold text-white mb-2 sm:mb-4">
            文件预览演示
          </h2>
          <p className="text-gray-400 text-sm sm:text-lg px-4">
            支持 20+ 种文件格式的现代化预览组件
          </p>
        </div>

        {/* 文件上传区域 */}
        <div className="max-w-6xl mx-auto mb-8 sm:mb-12">
          <div
            onDragEnter={handleDragEnter}
            onDragLeave={handleDragLeave}
            onDragOver={handleDragOver}
            onDrop={handleDrop}
            className={`bg-white/5 backdrop-blur-sm rounded-xl sm:rounded-2xl p-5 sm:p-8 border-2 border-dashed transition-all ${isDragging
              ? 'border-blue-500 bg-blue-500/10 scale-105'
              : 'border-white/20 hover:border-white/40'
              }`}
          >
            <input
              ref={fileInputRef}
              type="file"
              multiple
              onChange={handleFileUpload}
              className="hidden"
              id="file-upload"
              accept="*/*"
            />
            <label
              htmlFor="file-upload"
              className="flex flex-col items-center justify-center cursor-pointer"
            >
              <div className={`w-14 h-14 sm:w-20 sm:h-20 rounded-full bg-gradient-to-br from-blue-500 to-purple-600 flex items-center justify-center mb-3 sm:mb-4 transition-transform ${isDragging ? 'scale-110' : ''
                }`}>
                <Upload className="w-7 h-7 sm:w-10 sm:h-10 text-white" />
              </div>
              <h3 className="text-white text-base sm:text-xl font-medium mb-1.5 sm:mb-2">
                {isDragging ? '松开以上传文件' : '上传本地文件预览'}
              </h3>
              <p className="text-gray-400 text-xs sm:text-sm mb-3 sm:mb-4 px-2">
                {isDragging ? '将文件拖放到此处' : '支持图片、PDF、Word、Excel、视频、音频等格式'}
              </p>
              {!isDragging && (
                <div className="px-5 py-2.5 sm:px-6 sm:py-3 bg-gradient-to-r from-blue-500 to-purple-600 rounded-lg text-white text-sm sm:text-base font-medium hover:shadow-lg hover:scale-105 active:scale-95 transition-all">
                  选择文件或拖拽到此处
                </div>
              )}
            </label>
          </div>
        </div>

        {/* 已上传的文件列表 */}
        {uploadedFiles.length > 0 && (
          <div className="max-w-6xl mx-auto mb-8 sm:mb-12">
            <h2 className="text-xl sm:text-2xl font-bold text-white mb-4 sm:mb-6">已上传的文件</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3 sm:gap-6">
              {uploadedFiles.map((file, index) => {
                return (
                  <div
                    key={file.id}
                    className="group relative bg-white/5 backdrop-blur-sm rounded-xl sm:rounded-2xl p-4 sm:p-6 border border-white/10 hover:border-white/30 active:bg-white/10 transition-all duration-300"
                  >
                    <button
                      onClick={() => handleFileClick(index)}
                      className="w-full text-left"
                    >
                      <div className="flex items-start gap-3 sm:gap-4">
                        <div className="p-3 sm:p-4 rounded-xl bg-gradient-to-br from-green-500 to-teal-600 text-white group-hover:scale-110 transition-transform flex-shrink-0">
                          {getFileIcon(file.type)}
                        </div>
                        <div className="flex-1 min-w-0 pr-6 sm:pr-0">
                          <h3 className="text-white font-medium text-base sm:text-lg mb-1 sm:mb-2 truncate">
                            {file.name}
                          </h3>
                          <p className="text-gray-400 text-xs sm:text-sm truncate">
                            {file.type.split('/')[1]?.toUpperCase() || 'FILE'}
                          </p>
                          {file.size && (
                            <p className="text-gray-500 text-xs mt-1">
                              {formatFileSize(file.size)}
                            </p>
                          )}
                        </div>
                      </div>
                      <div className="mt-3 sm:mt-4 text-green-400 text-xs sm:text-sm font-medium group-hover:text-green-300">
                        点击预览 →
                      </div>
                    </button>

                    {/* 删除按钮 */}
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        handleRemoveFile(file.id);
                      }}
                      className="absolute top-3 right-3 sm:top-4 sm:right-4 w-7 h-7 sm:w-8 sm:h-8 rounded-full bg-red-500/80 hover:bg-red-500 flex items-center justify-center text-white opacity-100 sm:opacity-0 sm:group-hover:opacity-100 transition-all"
                      title="删除文件"
                    >
                      <X className="w-3.5 h-3.5 sm:w-4 sm:h-4" />
                    </button>
                  </div>
                );
              })}
            </div>
          </div>
        )}

        {/* 嵌入式预览演示 */}
        {allFiles.length > 0 && (
          <div className="max-w-6xl mx-auto mb-8 sm:mb-12">
            <h2 className="text-xl sm:text-2xl font-bold text-white mb-2">嵌入式预览 (FilePreviewEmbed)</h2>
            <p className="text-gray-400 text-sm mb-4 sm:mb-6">
              将预览组件直接嵌入到页面的 div 容器中,无需弹窗。下方容器高度固定为 520px。
            </p>
            <div
              className="bg-white/5 backdrop-blur-sm rounded-xl sm:rounded-2xl border border-white/10 overflow-hidden"
              style={{ height: 520 }}
            >
              <FilePreviewEmbed
                files={allFiles}
                currentIndex={embedIndex}
                onNavigate={setEmbedIndex}
              />
            </div>
          </div>
        )}
      </div>

      {/* 页脚 */}
      <footer className="max-w-6xl mx-auto mt-8 sm:mt-12 mb-6 sm:mb-8 px-3 sm:px-4 text-center pb-[env(safe-area-inset-bottom)]">
        <div className="text-gray-400 text-xs sm:text-sm">
          <p className="mb-2">
            Made with ❤️ by{' '}
            <a
              href="https://github.com/wh131462"
              target="_blank"
              rel="noopener noreferrer"
              className="text-blue-400 hover:text-blue-300 transition-colors"
            >
              EternalHeart
            </a>
          </p>
          <p className="flex flex-wrap items-center justify-center gap-1">
            <a
              href="https://github.com/wh131462/file-preview/blob/master/LICENSE"
              target="_blank"
              rel="noopener noreferrer"
              className="text-gray-500 hover:text-gray-400 transition-colors"
            >
              MIT License
            </a>
            <span>{' '} · {' '}</span>
            <a
              href="https://github.com/wh131462/file-preview"
              target="_blank"
              rel="noopener noreferrer"
              className="text-gray-500 hover:text-gray-400 transition-colors"
            >
              GitHub
            </a>
            <span>{' '} · {' '}</span>
            <a
              href="https://www.npmjs.com/package/@eternalheart/react-file-preview"
              target="_blank"
              rel="noopener noreferrer"
              className="text-gray-500 hover:text-gray-400 transition-colors"
            >
              npm
            </a>
            <span>{' '} · {' '}</span>
            <a
              href={DOCS_URL}
              target="_blank"
              rel="noopener noreferrer"
              className="text-gray-500 hover:text-gray-400 transition-colors"
            >
              API Docs
            </a>
          </p>
        </div>
      </footer>

      <FilePreviewModal
        files={allFiles}
        currentIndex={currentFileIndex}
        isOpen={isPreviewOpen}
        onClose={() => setIsPreviewOpen(false)}
        onNavigate={setCurrentFileIndex}
      />
    </div>
  );
}

export default App;

// packages/vue-example/src/App.vue
<script setup lang="ts">
import { ref, onUnmounted } from 'vue';
import {
  FilePreviewModal,
  FilePreviewEmbed,
  VERSION,
  type PreviewFile,
  type PreviewFileInput,
} from '@eternalheart/vue-file-preview';
import '@eternalheart/vue-file-preview/style.css';
import {
  FileText,
  Image as ImageIcon,
  FileSpreadsheet,
  Video,
  Music,
  Upload,
  X,
  Package,
  BookOpen,
  Code,
} from 'lucide-vue-next';
import iconSvg from './assets/icon.svg';

// 环境检测
const isDev = import.meta.env.DEV;
const DOCS_URL = isDev
  ? 'http://localhost:4801/file-preview/docs/'
  : 'https://wh131462.github.io/file-preview/docs/';
const REACT_EXAMPLE_URL = isDev
  ? 'http://localhost:4800/'
  : 'https://wh131462.github.io/file-preview/';

const isPreviewOpen = ref(false);
const currentFileIndex = ref(0);
const embedIndex = ref(0);
const uploadedFiles = ref<PreviewFile[]>([]);
const allFiles = ref<PreviewFileInput[]>([]);
const isDragging = ref(false);
const fileInputRef = ref<HTMLInputElement | null>(null);

const getFileIcon = (type: string) => {
  if (type.startsWith('image/')) return ImageIcon;
  if (type.includes('pdf')) return FileText;
  if (type.includes('spreadsheet')) return FileSpreadsheet;
  if (type.startsWith('video/')) return Video;
  if (type.startsWith('audio/')) return Music;
  return FileText;
};

const handleFileClick = (index: number) => {
  currentFileIndex.value = index;
  isPreviewOpen.value = true;
};

const processFiles = (files: FileList | null) => {
  if (!files || files.length === 0) return;

  const newFiles: PreviewFile[] = Array.from(files).map((file, index) => ({
    id: `uploaded-${Date.now()}-${index}`,
    name: file.name,
    url: URL.createObjectURL(file),
    type: file.type || 'application/octet-stream',
    size: file.size,
  }));

  uploadedFiles.value = [...uploadedFiles.value, ...newFiles];
  allFiles.value = [...allFiles.value, ...newFiles];
};

const handleFileUpload = (event: Event) => {
  const input = event.target as HTMLInputElement;
  processFiles(input.files);
  if (fileInputRef.value) fileInputRef.value.value = '';
};

const handleDragEnter = (e: DragEvent) => {
  e.preventDefault();
  e.stopPropagation();
  isDragging.value = true;
};

const handleDragLeave = (e: DragEvent) => {
  e.preventDefault();
  e.stopPropagation();
  if (e.currentTarget === e.target) {
    isDragging.value = false;
  }
};

const handleDragOver = (e: DragEvent) => {
  e.preventDefault();
  e.stopPropagation();
};

const handleDrop = (e: DragEvent) => {
  e.preventDefault();
  e.stopPropagation();
  isDragging.value = false;
  const files = e.dataTransfer?.files || null;
  processFiles(files);
};

const handleRemoveFile = (fileId: string) => {
  const fileToRemove = uploadedFiles.value.find((f) => f.id === fileId);
  if (fileToRemove) URL.revokeObjectURL(fileToRemove.url);

  uploadedFiles.value = uploadedFiles.value.filter((f) => f.id !== fileId);
  allFiles.value = allFiles.value.filter((f) => {
    if (typeof f === 'string') return true;
    if (f instanceof File) return true;
    return (f as PreviewFile).id !== fileId;
  });
};

const formatFileSize = (bytes?: number) => {
  if (!bytes) return '';
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
};

onUnmounted(() => {
  // 释放所有 blob URL
  uploadedFiles.value.forEach((f) => URL.revokeObjectURL(f.url));
});
</script>

<template>
  <div class="min-h-screen bg-gradient-to-br from-gray-900 via-gray-800 to-gray-900">
    <!-- 导航栏 -->
    <nav class="bg-black/20 backdrop-blur-xl border-b border-white/10 sticky top-0 z-40">
      <div class="container mx-auto px-3 py-3 sm:px-4 sm:py-4">
        <div class="flex items-center justify-between">
          <div class="flex items-center gap-2 sm:gap-3 min-w-0">
            <img :src="iconSvg" alt="logo" class="w-8 h-8 sm:w-10 sm:h-10 rounded-xl flex-shrink-0" />
            <div class="flex flex-col items-start min-w-0">
              <h1 class="text-base sm:text-xl font-bold text-white truncate">Vue File Preview</h1>
              <p class="text-[10px] sm:text-xs text-gray-400 truncate max-w-[160px] sm:max-w-none">
                @eternalheart/vue-file-preview@{{ VERSION }}
              </p>
            </div>
          </div>

          <div class="flex items-center gap-1.5 sm:gap-3 flex-shrink-0">
            <!-- 框架切换器 -->
            <div class="flex items-center gap-0.5 p-0.5 rounded-lg bg-white/5 border border-white/10">
              <a
                :href="REACT_EXAMPLE_URL"
                class="px-2.5 py-1.5 sm:px-3 sm:py-1.5 rounded-md text-xs sm:text-sm font-medium text-gray-400 hover:text-white hover:bg-white/5 transition-all"
                title="切换到 React 版本"
              >
                React
              </a>
              <span
                class="px-2.5 py-1.5 sm:px-3 sm:py-1.5 rounded-md text-xs sm:text-sm font-medium bg-gradient-to-r from-emerald-500 to-teal-600 text-white shadow-md"
              >
                Vue
              </span>
            </div>

            <a
              href="https://github.com/wh131462/file-preview"
              target="_blank"
              rel="noopener noreferrer"
              class="hidden sm:flex items-center gap-2 px-2.5 py-2 sm:px-4 sm:py-2 rounded-lg bg-white/5 hover:bg-white/10 active:bg-white/15 text-white transition-all hover:scale-105"
            >
              <Code class="w-4 h-4 sm:w-5 sm:h-5" />
              <span class="hidden sm:inline">GitHub</span>
            </a>
            <a
              href="https://www.npmjs.com/package/@eternalheart/vue-file-preview"
              target="_blank"
              rel="noopener noreferrer"
              class="hidden sm:flex items-center gap-2 px-2.5 py-2 sm:px-4 sm:py-2 rounded-lg bg-white/5 hover:bg-white/10 active:bg-white/15 text-white transition-all hover:scale-105"
            >
              <Package class="w-4 h-4 sm:w-5 sm:h-5" />
              <span class="hidden sm:inline">npm</span>
            </a>
            <a
              :href="DOCS_URL"
              target="_blank"
              rel="noopener noreferrer"
              class="hidden sm:flex items-center gap-2 px-2.5 py-2 sm:px-4 sm:py-2 rounded-lg bg-gradient-to-r from-blue-500 to-purple-600 text-white transition-all hover:scale-105 hover:shadow-lg active:scale-95"
            >
              <BookOpen class="w-4 h-4 sm:w-5 sm:h-5" />
              <span class="hidden sm:inline">API Docs</span>
            </a>
          </div>
        </div>
      </div>
    </nav>

    <div class="container mx-auto px-3 sm:px-4 py-8 sm:py-16">
      <div class="text-center mb-8 sm:mb-12">
        <h2 class="text-2xl sm:text-4xl font-bold text-white mb-2 sm:mb-4">文件预览演示</h2>
        <p class="text-gray-400 text-sm sm:text-lg px-4">支持 20+ 种文件格式的现代化预览组件 · Vue 3 版本</p>
      </div>

      <!-- 文件上传区域 -->
      <div class="max-w-6xl mx-auto mb-8 sm:mb-12">
        <div
          @dragenter="handleDragEnter"
          @dragleave="handleDragLeave"
          @dragover="handleDragOver"
          @drop="handleDrop"
          :class="[
            'bg-white/5 backdrop-blur-sm rounded-xl sm:rounded-2xl p-5 sm:p-8 border-2 border-dashed transition-all',
            isDragging ? 'border-emerald-500 bg-emerald-500/10 scale-105' : 'border-white/20 hover:border-white/40',
          ]"
        >
          <input
            ref="fileInputRef"
            type="file"
            multiple
            class="hidden"
            id="file-upload"
            accept="*/*"
            @change="handleFileUpload"
          />
          <label for="file-upload" class="flex flex-col items-center justify-center cursor-pointer">
            <div
              :class="[
                'w-14 h-14 sm:w-20 sm:h-20 rounded-full bg-gradient-to-br from-emerald-500 to-teal-600 flex items-center justify-center mb-3 sm:mb-4 transition-transform',
                isDragging && 'scale-110',
              ]"
            >
              <Upload class="w-7 h-7 sm:w-10 sm:h-10 text-white" />
            </div>
            <h3 class="text-white text-base sm:text-xl font-medium mb-1.5 sm:mb-2">
              {{ isDragging ? '松开以上传文件' : '上传本地文件预览' }}
            </h3>
            <p class="text-gray-400 text-xs sm:text-sm mb-3 sm:mb-4 px-2">
              {{ isDragging ? '将文件拖放到此处' : '支持图片、PDF、Word、Excel、视频、音频等格式' }}
            </p>
            <div
              v-if="!isDragging"
              class="px-5 py-2.5 sm:px-6 sm:py-3 bg-gradient-to-r from-emerald-500 to-teal-600 rounded-lg text-white text-sm sm:text-base font-medium hover:shadow-lg hover:scale-105 active:scale-95 transition-all"
            >
              选择文件或拖拽到此处
            </div>
          </label>
        </div>
      </div>

      <!-- 已上传文件列表 -->
      <div v-if="uploadedFiles.length > 0" class="max-w-6xl mx-auto mb-8 sm:mb-12">
        <h2 class="text-xl sm:text-2xl font-bold text-white mb-4 sm:mb-6">已上传的文件</h2>
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3 sm:gap-6">
          <div
            v-for="(file, index) in uploadedFiles"
            :key="file.id"
            class="group relative bg-white/5 backdrop-blur-sm rounded-xl sm:rounded-2xl p-4 sm:p-6 border border-white/10 hover:border-white/30 active:bg-white/10 transition-all duration-300"
          >
            <button class="w-full text-left" @click="handleFileClick(index)">
              <div class="flex items-start gap-3 sm:gap-4">
                <div
                  class="p-3 sm:p-4 rounded-xl bg-gradient-to-br from-emerald-500 to-teal-600 text-white group-hover:scale-110 transition-transform flex-shrink-0"
                >
                  <component :is="getFileIcon(file.type)" class="w-8 h-8" />
                </div>
                <div class="flex-1 min-w-0 pr-6 sm:pr-0">
                  <h3 class="text-white font-medium text-base sm:text-lg mb-1 sm:mb-2 truncate">
                    {{ file.name }}
                  </h3>
                  <p class="text-gray-400 text-xs sm:text-sm truncate">
                    {{ file.type.split('/')[1]?.toUpperCase() || 'FILE' }}
                  </p>
                  <p v-if="file.size" class="text-gray-500 text-xs mt-1">
                    {{ formatFileSize(file.size) }}
                  </p>
                </div>
              </div>
              <div class="mt-3 sm:mt-4 text-emerald-400 text-xs sm:text-sm font-medium group-hover:text-emerald-300">
                点击预览 →
              </div>
            </button>

            <button
              class="absolute top-3 right-3 sm:top-4 sm:right-4 w-7 h-7 sm:w-8 sm:h-8 rounded-full bg-red-500/80 hover:bg-red-500 flex items-center justify-center text-white opacity-100 sm:opacity-0 sm:group-hover:opacity-100 transition-all"
              title="删除文件"
              @click.stop="handleRemoveFile(file.id)"
            >
              <X class="w-3.5 h-3.5 sm:w-4 sm:h-4" />
            </button>
          </div>
        </div>
      </div>

      <!-- 嵌入式预览演示 -->
      <div v-if="allFiles.length > 0" class="max-w-6xl mx-auto mb-8 sm:mb-12">
        <h2 class="text-xl sm:text-2xl font-bold text-white mb-2">嵌入式预览 (FilePreviewEmbed)</h2>
        <p class="text-gray-400 text-sm mb-4 sm:mb-6">
          将预览组件直接嵌入到页面的 div 容器中,无需弹窗。下方容器高度固定为 520px。
        </p>
        <div
          class="bg-white/5 backdrop-blur-sm rounded-xl sm:rounded-2xl border border-white/10 overflow-hidden"
          :style="{ height: '520px' }"
        >
          <FilePreviewEmbed
            :files="allFiles"
            :current-index="embedIndex"
            @navigate="(i: number) => (embedIndex = i)"
          />
        </div>
      </div>
    </div>

    <!-- 页脚 -->
    <footer class="max-w-6xl mx-auto mt-8 sm:mt-12 mb-6 sm:mb-8 px-3 sm:px-4 text-center pb-[env(safe-area-inset-bottom)]">
      <div class="text-gray-400 text-xs sm:text-sm">
        <p class="mb-2">
          Made with ❤️ by
          <a
            href="https://github.com/wh131462"
            target="_blank"
            rel="noopener noreferrer"
            class="text-emerald-400 hover:text-emerald-300 transition-colors"
          >
            EternalHeart
          </a>
        </p>
        <p class="flex flex-wrap items-center justify-center gap-1">
          <a
            href="https://github.com/wh131462/file-preview/blob/master/LICENSE"
            target="_blank"
            rel="noopener noreferrer"
            class="text-gray-500 hover:text-gray-400 transition-colors"
          >
            MIT License
          </a>
          <span> · </span>
          <a
            href="https://github.com/wh131462/file-preview"
            target="_blank"
            rel="noopener noreferrer"
            class="text-gray-500 hover:text-gray-400 transition-colors"
          >
            GitHub
          </a>
          <span> · </span>
          <a
            href="https://www.npmjs.com/package/@eternalheart/vue-file-preview"
            target="_blank"
            rel="noopener noreferrer"
            class="text-gray-500 hover:text-gray-400 transition-colors"
          >
            npm
          </a>
          <span> · </span>
          <a
            :href="DOCS_URL"
            target="_blank"
            rel="noopener noreferrer"
            class="text-gray-500 hover:text-gray-400 transition-colors"
          >
            API Docs
          </a>
        </p>
      </div>
    </footer>

    <FilePreviewModal
      :files="allFiles"
      :current-index="currentFileIndex"
      :is-open="isPreviewOpen"
      @close="isPreviewOpen = false"
      @navigate="(i: number) => (currentFileIndex = i)"
    />
  </div>
</template>
